<?php
$all_books = $db->orderBy('id', 'DESC')->get('books');
$page_title = 'All Library Books';
if (isset($_GET['category_id']) && !empty($_GET['category_id']) && isset($_GET['author_id']) && !empty($_GET['author_id'])) {
    $all_books = $db->orderBy('id', 'DESC')->where('category_id', secure_data(($_GET['category_id'])))->where('author_id', secure_data(($_GET['author_id'])))->get('books');
    $author_name = $db->where('id', secure_data(($_GET['author_id'])))->getOne('book_authors')->names;
    $category_name = $db->where('id', secure_data(($_GET['category_id'])))->getOne('categories')->names;
    $page_title = 'All ' . $category_name . '  ' . $author_name . ' Books';
} else if (isset($_GET['category_id']) && !empty($_GET['category_id'])) {
    $all_books = $db->orderBy('id', 'DESC')->where('category_id', secure_data(($_GET['category_id'])))->get('books');
    $page_title = 'All ' . $db->where('id', secure_data(($_GET['category_id'])))->getOne('categories')->name . ' Books';
} else if (isset($_GET['author_id']) && !empty($_GET['author_id'])) {
    $all_books = $db->orderBy('id', 'DESC')->where('author_id', secure_data(($_GET['author_id'])))->get('books');
    $page_title = 'All ' . $db->where('id', secure_data(($_GET['author_id'])))->getOne('book_authors')->names . ' Books';
}

?>

<div class="main-content">


    <div class="page-content">
        <div class="container-fluid">

            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                        <h4 class="mb-sm-0"><?= $page_title ?></h4>

                        <div class="page-title-right">
                            <ol class="breadcrumb m-0">
                                <li class="breadcrumb-item"><a href="javascript: void(0);">Home</a></li>
                                <li class="breadcrumb-item active">All Books</li>
                            </ol>
                        </div>

                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">

                        <div class="card-body">
                            <div class="listjs-table" id="customerList">
                                <div class="row g-4 mb-3">
                                    <div class="col-sm-auto">
                                        <?php if ($global_var['user']['user_type'] != 'stud') { ?>
                                            <div>
                                                <a data-bs-toggle="modal" data-bs-target="#register" type="button" class="btn btn-success add-btn"><i class="ri-add-line align-bottom me-1"></i> Add New Book</a>

                                            </div>
                                        <?php } ?>
                                    </div>
                                    <div class="col-sm-auto">
                                        <div>


                                        </div>
                                    </div>

                                    <div class="col-sm">
                                        <div class="d-flex justify-content-sm-end">
                                            <div class="search-box ms-2">
                                                <a data-bs-toggle="modal" data-bs-target="#filter_" type="button" class="btn btn-primary add-btn"><i class="ri-filter-line align-bottom me-1"></i> Filter Books</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="table-responsive mt-3 mb-1">
                                    <table id="myTable" class="table table-bordered table-striped">
                                        <thead class="table-light">
                                            <tr>
                                                <th scope="col">
                                                    S/No.
                                                </th>
                                                <th class="sort" data-sort="title">Title</th>
                                                <th class="sort" data-sort="description">Category</th>
                                                <th class="sort" data-sort="date">Aurthor</th>
                                                <th class="sort" data-sort="date">ISBN</th>
                                                <?php if ($global_var['user']['user_type'] != 'stud') { ?>
                                                    <th class="sort" data-sort="date">Registered On</th>
                                                    <th class="sort" data-sort="date">Registered By</th>
                                                    <th class="sort" data-sort="action">Action</th>
                                                <?php } else { ?>
                                                    <th class="sort" data-sort="date">Status</th>
                                                <?php } ?>
                                            </tr>
                                        </thead>
                                        <tbody class="list form-check-all">

                                            <?php
                                            $sn = 0;
                                            foreach ($all_books as $value):
                                                $available_bks = $db->where("book_id", $value->id)->getOne("current_books");

                                                $sn++;
                                            ?>
                                                <tr>
                                                    <th scope="row">
                                                        <?= $sn ?>
                                                    </th>
                                                    <td><?= $value->title ?></td>
                                                    <td class="title"><?= $db->where("id", $value->category_id)->getOne("categories")->name ?></td>
                                                    <td class="description"><?= $db->where("id", $value->author_id)->getOne("book_authors")->names ?></td>
                                                    <td><?= $value->isbn ?></td>
                                                    <?php if ($global_var['user']['user_type'] != 'stud') { ?>
                                                        <td class="date"><?= date('d/m/Y', strtotime($value->date_created)) ?></td>

                                                        <td><?= $db->where('id', $value->created_by)->getOne('users')->firstname ?></td>
                                                        <td>
                                                            <div class="d-flex gap-2">
                                                                <a title="View Details" class="btn btn-sm btn-primary" href="index.php?page=book_details&id=<?= $value->id ?>"><i class="fas fa-eye "></i></a>


                                                            </div>
                                                        </td>
                                                    <?php } else { ?>
                                                        <td><?php if (exists("book_copies", "WHERE book_id = '" . $value->id . "' AND status = 'available'")) {
                                                                echo '<span class="badge bg-info">Available</span>';
                                                            } else {
                                                                echo '<span class="badge bg-danger">Not Available</span>';
                                                            } ?></td>
                                                    <?php } ?>
                                                </tr>
                                            <?php endforeach; ?>
                                        </tbody>
                                    </table>

                                </div>
                            </div>
                        </div><!-- end card -->
                    </div>
                    <!-- end col -->
                </div>
                <!-- end col -->
            </div>
            <!-- end row -->



        </div>
    </div>


    <script type="text/javascript">
        $('#filter_book').on('submit', function(e) {

            e.preventDefault();
            $.ajax({
                url: request() + '?file=books&action=filter_by_category',
                method: 'POST',
                data: new FormData(this),
                contentType: false,
                processData: false,
                cache: false,
                success: function(response) {
                    console.log(response);
                    if (response.status == 200) {
                        Swal.fire({
                            title: "Good job!",
                            text: response.message,
                            icon: "success",
                            showConfirmButton: true,
                        });
                        setTimeout(function() {
                            window.location.href = response.url;
                        }, 2e3);

                    } else {
                        Swal.fire({
                            title: "Oops!",
                            text: response.message,
                            icon: "error",
                            cancelButtonClass: "btn btn-danger ml-2 mt-2",
                            confirmButtonColor: "#6c757d"
                        });
                    }
                }
            });
        });
    </script>