<?php
$all_books = $db->orderBy('id', 'DESC')->get('books');
$page_title = 'All Library Books';
if (isset($_GET['id']) && !empty($_GET['id'])) {
    $all_books = $db->orderBy('id', 'DESC')->where('category_id', __secure(($_GET['id'])))->get('books');
    $page_title = 'All ' . $db->where('id', __secure(($_GET['id'])))->getOne('categories')->name . ' Books';
}
?>

<div class="main-content">


    <div class="page-content">
        <div class="container-fluid">

            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                        <h4 class="mb-sm-0"><?= $page_title ?></h4>

                        <div class="page-title-right">
                            <ol class="breadcrumb m-0">
                                <li class="breadcrumb-item"><a href="javascript: void(0);">Home</a></li>
                                <li class="breadcrumb-item active">All Books</li>
                            </ol>
                        </div>

                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">

                        <div class="card-body">
                            <div class="listjs-table" id="customerList">
                                <div class="row g-4 mb-3">
                                    <div class="col-sm-auto">
                                        <?php if ($the_ken['user']['user_type'] != 'stud') { ?>
                                            <div>
                                                <a data-bs-toggle="modal" data-bs-target="#register" type="button" class="btn btn-success add-btn"><i class="ri-add-line align-bottom me-1"></i> Add New Book</a>

                                            </div>
                                        <?php } ?>
                                    </div>
                                    <div class="col-sm-auto">
                                        <div>


                                        </div>
                                    </div>
                                    <div class="col-sm">
                                        <div class="d-flex justify-content-sm-end">
                                            <div class="search-box ms-2">
                                                <a data-bs-toggle="modal" data-bs-target="#filter_" type="button" class="btn btn-primary add-btn"><i class="ri-filter-line align-bottom me-1"></i> Filter By Category</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="table-responsive mt-3 mb-1">
                                    <table id="myTable" class="table table-bordered table-striped">
                                        <thead class="table-light">
                                            <tr>
                                                <th scope="col">
                                                    S/No.
                                                </th>
                                                <th class="sort" data-sort="title">Title</th>
                                                <th class="sort" data-sort="description">Category</th>
                                                <th class="sort" data-sort="date">Aurthor</th>
                                                <th class="sort" data-sort="date">ISBN</th>
                                                <?php if ($the_ken['user']['user_type'] != 'stud') { ?>
                                                    <th class="sort" data-sort="date">Registered On</th>
                                                    <th class="sort" data-sort="date">Registered By</th>
                                                    <th class="sort" data-sort="action">Action</th>
                                                <?php } else { ?>
                                                    <th class="sort" data-sort="date">Available Copies</th>
                                                <?php } ?>
                                            </tr>
                                        </thead>
                                        <tbody class="list form-check-all">

                                            <?php
                                            $sn = 0;
                                            foreach ($all_books as $value):
                                                $available_bks = $db->where("book_id", $value->id)->getOne("current_books");

                                                $sn++;
                                            ?>
                                                <tr>
                                                    <th scope="row">
                                                        <?= $sn ?>
                                                    </th>
                                                    <td><?= $value->title ?></td>
                                                    <td class="title"><?= $db->where("id", $value->category_id)->getOne("categories")->name ?></td>
                                                    <td class="description"><?= $value->author ?></td>
                                                    <td><?= $value->isbn ?></td>
                                                    <?php if ($the_ken['user']['user_type'] != 'stud') { ?>
                                                        <td class="date"><?= date('d/m/Y', strtotime($value->date_created)) ?></td>

                                                        <td><?= $db->where('id', $value->created_by)->getOne('users')->firstname ?></td>
                                                        <td>
                                                            <div class="d-flex gap-2">
                                                                <a title="Edit Class" class="btn btn-sm btn-primary" href="index.php?page=edit_book&id=<?= $value->id ?>"><i class="fas fa-edit "></i></a>

                                                                <button title="Edit Class" onclick="deleteItem('<?= $value->id ?>')" class="btn btn-sm btn-danger"><i class="fas fa-trash"></i></button>

                                                            </div>
                                                        </td>
                                                    <?php } else { ?>
                                                        <td><?= $available_bks->no_of_copies ?></td>
                                                    <?php } ?>
                                                </tr>
                                            <?php endforeach; ?>
                                        </tbody>
                                    </table>
                                    <div class="noresult" style="display: none">
                                        <div class="text-center">
                                            <lord-icon src="https://cdn.lordicon.com/msoeawqm.json" trigger="loop" colors="primary:#121331,secondary:#08a88a" style="width:75px;height:75px"></lord-icon>
                                            <h5 class="mt-2">Sorry! No Result Found</h5>
                                            <p class="text-muted mb-0">We've searched more than 150+ Orders We did not find any orders for you search.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div><!-- end card -->
                    </div>
                    <!-- end col -->
                </div>
                <!-- end col -->
            </div>
            <!-- end row -->



        </div>
    </div>
    <!-- Add new Borrow request Modal -->
    <div id="filter_" class="modal fade fadeInUp" tabindex="-1" aria-labelledby="fadeInUpModalLabel" aria-hidden="true" style="display: none;">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="fadeInUpModalLabel">Filter Books By Category</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="filter_book">
                        <div class="row gy-4">

                            <div class="col-xxl-3 col-md-12">
                                <div>
                                    <label for="basiInput" class="form-label">Book Category</label>
                                    <select name="id" class="form-control selectpicker" data-live-search="true">
                                        <option value="">--Select Category--</option>
                                        <?php foreach ($db->get("categories") as $value) { ?>
                                            <option value="<?= $value->id ?>"><?= $value->name  ?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <hr>
                        <div class="modal-footer mt-4">
                            <button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary ">Filter Books</button>
                        </div>
                </div>
                </form>

            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

    <script type="text/javascript">
        function deleteItem(id) {
            // Show SweetAlert confirmation dialog
            Swal.fire({
                title: 'Are you sure?',
                text: "This action cannot be undone!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    // If confirmed, proceed with AJAX request
                    $.ajax({
                        url: request() + '?f=books&s=delete',
                        method: 'POST',
                        data: {
                            id: id
                        },
                        success: function(data) {
                            console.log(data);
                            if (data.status == 200) {
                                iziToast.success({
                                    title: 'Info',
                                    message: data.message,
                                    position: 'topRight'
                                });
                                setTimeout(function() {
                                    location.reload();
                                }, 1000);
                            } else {
                                iziToast.error({
                                    title: 'Alert',
                                    message: data.message,
                                    position: 'topRight'
                                });
                            }
                        }
                    });
                }
            });
        }
        $('#filter_book').on('submit', function(e) {

            e.preventDefault();
            $.ajax({
                url: request() + '?f=books&s=filter_by_category',
                method: 'POST',
                data: new FormData(this),
                contentType: false,
                processData: false,
                cache: false,
                success: function(response) {
                    console.log(response);
                    if (response.status == 200) {
                        Swal.fire({
                            title: "Good job!",
                            text: response.message,
                            icon: "success",
                            showConfirmButton: true,
                        });
                        setTimeout(function() {
                            window.location.href = response.url;
                        }, 2e3);

                    } else {
                        Swal.fire({
                            title: "Oops!",
                            text: response.message,
                            icon: "error",
                            cancelButtonClass: "btn btn-danger ml-2 mt-2",
                            confirmButtonColor: "#6c757d"
                        });
                    }
                }
            });
        });
    </script>