<?php
$all_students = $db->orderBy('id', 'DESC')->where('user_type', 'stud')->get('users');
$page_title = 'All Students';
if (isset($_GET['id']) && !empty($_GET['id'])) {
    $all_students = $db->orderBy('id', 'DESC')->where('class_id', secure_data(($_GET['id'])))->where('user_type', 'stud')->get('users');

    $page_title = 'All ' . $db->where('id', secure_data(($_GET['id'])))->getOne('classes')->name . ' Students';
}

?>
<div class="main-content">

    <div class="page-content">
        <div class="container-fluid">

            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                        <h4 class="mb-sm-0"><?= $page_title ?></h4>

                        <div class="page-title-right">
                            <ol class="breadcrumb m-0">
                                <li class="breadcrumb-item"><a href="javascript: void(0);">Home</a></li>
                                <li class="breadcrumb-item active">Students</li>
                            </ol>
                        </div>

                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">

                        <div class="card-body">
                            <div class="listjs-table" id="customerList">

                                <div class="col-sm">
                                    <div class="d-flex justify-content-sm-end">
                                        <div class="search-box ms-2">
                                            <a data-bs-toggle="modal" data-bs-target="#filter_s" type="button" class="btn btn-primary add-btn"><i class="ri-filter-line align-bottom me-1"></i> Filter By Class</a>
                                        </div>
                                    </div>
                                </div>

                                <div class="table-responsive mt-3 mb-1">
                                    <table id="myTable" class="table table-bordered table-striped">
                                        <thead class="">
                                            <tr>
                                                <th scope="col">
                                                    S/No.
                                                </th>
                                                <th class="sort" data-sort="title">Student Name</th>
                                                <th class="sort" data-sort="description">Class</th>
                                                <th class="sort" data-sort="date">Email</th>
                                                <th class="sort" data-sort="date">Registered On</th>
                                                <th class="sort" data-sort="action">Action</th>
                                            </tr>
                                        </thead>
                                        <tbody class="list form-check-all">

                                            <?php
                                            $sn = 0;
                                            foreach ($all_students as $value):
                                                // $db->where("id", $value->category_id)->getOne("categories")->name

                                                $sn++;
                                            ?>
                                                <tr>
                                                    <th scope="row">
                                                        <?= $sn ?>
                                                    </th>
                                                    <td><?= $value->firstname . ' ' . $value->lastname ?></td>

                                                    <td><?= $db->where("id", $value->class_id)->getOne("classes")->abbrev ?></td>
                                                    <td><?= $value->email ?></td>
                                                    <td class="date"><?= date('d/m/Y', strtotime($value->date_created)) ?></td>
                                                    <td>
                                                        <div class="d-flex gap-2">
                                                            <div class="d-flex gap-2">
                                                                <a title="View Profile" class="btn btn-sm btn-primary" href="index.php?page=user_profile&id=<?= $value->id ?>">
                                                                    <i class="fas fa-eye"></i> View Profile
                                                                </a>


                                                            </div>


                                                        </div>
                                                    </td>
                                                </tr>
                                            <?php endforeach; ?>
                                        </tbody>
                                    </table>

                                </div>
                            </div>
                        </div><!-- end card -->
                    </div>
                    <!-- end col -->
                </div>
                <!-- end col -->
            </div>
            <!-- end row -->



        </div>
    </div>
    <!-- Modal fadeInUp -->
    <div id="register" class="modal fade fadeInUp" tabindex="-1" aria-labelledby="fadeInUpModalLabel" aria-hidden="true" style="display: none;">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="fadeInUpModalLabel">Add New Class</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="add_class">
                        <div class="row gy-4">

                            <!--end col-->
                            <div class="col-xxl-3 col-md-12">
                                <div>
                                    <label for="labelInput" class="form-label">Class Name </label>
                                    <input type="text" name="name" class="form-control">
                                </div>
                            </div>
                            <!--end col-->
                            <!--end col-->
                            <div class="col-xxl-3 col-md-12">
                                <div>
                                    <label for="labelInput" class="form-label">Class Abbrev </label>
                                    <input type="text" name="abbrev" class="form-control">
                                </div>
                            </div>
                            <!--end col-->





                        </div>
                        <hr>
                        <div class="modal-footer mt-4">
                            <button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary ">Add New Class</button>
                        </div>
                </div>
                </form>

            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <!-- Add new Borrow request Modal -->
    <div id="filter_s" class="modal fade fadeInUp" tabindex="-1" aria-labelledby="fadeInUpModalLabel" aria-hidden="true" style="display: none;">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="fadeInUpModalLabel">Filter Students By Class</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="filter_book">
                        <input type="text" value="<?= $page ?>" name="page" hidden />
                        <div class="row gy-4">

                            <div class="col-xxl-3 col-md-12">
                                <div>
                                    <label for="basiInput" class="form-label">Class</label>
                                    <select name="id" class="form-control selectpicker" data-live-search="true">
                                        <option value="">--Select Category--</option>
                                        <?php foreach ($db->get("classes") as $value) { ?>
                                            <option value="<?= $value->id ?>"><?= $value->name  ?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <hr>
                        <div class="modal-footer mt-4">
                            <button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary ">Filter Students</button>
                        </div>
                </div>
                </form>

            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

    <script type="text/javascript">
        function remImage(id) {
            // Show SweetAlert confirmation dialog
            Swal.fire({
                title: 'Are you sure?',
                text: "This action cannot be undone!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    // If confirmed, proceed with AJAX request
                    $.ajax({
                        url: request() + '?file=classes&action=delete_class',
                        method: 'POST',
                        data: {
                            id: id
                        },
                        success: function(data) {
                            console.log(data);
                            if (data.status == 200) {
                                iziToast.success({
                                    title: 'Info',
                                    message: data.message,
                                    position: 'topRight'
                                });
                                setTimeout(function() {
                                    location.reload();
                                }, 1000);
                            } else {
                                iziToast.error({
                                    title: 'Alert',
                                    message: data.message,
                                    position: 'topRight'
                                });
                            }
                        }
                    });
                }
            });
        }

        $('#add_class').on('submit', function(e) {

            e.preventDefault();
            $.ajax({
                url: request() + '?file=classes&action=add_new_class',
                method: 'POST',
                data: new FormData(this),
                contentType: false,
                processData: false,
                cache: false,
                success: function(response) {
                    console.log(response);
                    if (response.status == 200) {
                        Swal.fire({
                            title: "Good job!",
                            text: response.message,
                            icon: "success",
                            showConfirmButton: true,
                        });
                        setTimeout(function() {
                            window.location.href = response.url;
                        }, 2e3);

                    } else {
                        Swal.fire({
                            title: "Oops!",
                            text: response.message,
                            icon: "error",
                            cancelButtonClass: "btn btn-danger ml-2 mt-2",
                            confirmButtonColor: "#6c757d"
                        });
                    }
                }
            });
        });
        $('#filter_student').on('submit', function(e) {

            e.preventDefault();
            $.ajax({
                url: request() + '?file=users&action=filter_by_class',
                method: 'POST',
                data: new FormData(this),
                contentType: false,
                processData: false,
                cache: false,
                success: function(response) {
                    console.log(response);
                    if (response.status == 200) {
                        Swal.fire({
                            title: "Good job!",
                            text: response.message,
                            icon: "success",
                            showConfirmButton: true,
                        });
                        setTimeout(function() {
                            window.location.href = response.url;
                        }, 2e3);

                    } else {
                        Swal.fire({
                            title: "Oops!",
                            text: response.message,
                            icon: "error",
                            cancelButtonClass: "btn btn-danger ml-2 mt-2",
                            confirmButtonColor: "#6c757d"
                        });
                    }
                }
            });
        });
    </script>