<?php
$book_details = $db->where('id', secure_data($_GET['book_id']))->getOne('books');
$page_title = 'All ' . (empty($book_details) ? '' : $book_details->title) . ' Book Copies';
// if (isset($_GET['id']) && !empty($_GET['id'])) {
//     $current_books = $db->orderBy('id', 'DESC')->where('category_id', secure_data(($_GET['id'])))->get('books');
//     $page_title = 'All ' . $db->where('id', secure_data(($_GET['id'])))->getOne('categories')->name . ' Books';
// }
$all_book_copies = $db->where('book_id', $book_details->id)->get("book_copies");
?>
<div class="main-content">


    <div class="page-content">
        <div class="container-fluid">

            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                        <h4 class="mb-sm-0"><?= $page_title ?></h4>

                        <div class="page-title-right">
                            <ol class="breadcrumb m-0">
                                <li class="breadcrumb-item"><a href="javascript: void(0);">Home</a></li>
                                <li class="breadcrumb-item active">Current Books</li>
                            </ol>
                        </div>

                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">

                        <div class="card-body">
                            <div class="listjs-table" id="customerList">
                                <div class="col-sm-auto">

                                    <div>
                                        <a data-bs-toggle="modal" data-bs-target="#add_new_book_copy_modal" type="button" class="btn btn-success add-btn"><i class="ri-add-line align-bottom me-1"></i> Add New Book Book Copy</a>

                                    </div>

                                </div>
                                <div class="row g-4 mb-3">
                                    <div class="col-sm">
                                        <div class="d-flex justify-content-sm-end">
                                            <div class="search-box ms-2">
                                                <a data-bs-toggle="modal" data-bs-target="#filter_" type="button" class="btn btn-primary add-btn"><i class="ri-filter-line align-bottom me-1"></i> Filter By Category</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="table-responsive mt-3 mb-1">
                                    <table id="myTable" class="table table-bordered table-striped">
                                        <thead class="table-light">
                                            <tr>
                                                <th scope="col">
                                                    S/No.
                                                </th>
                                                <th class="sort" data-sort="date">Book Copy No.</th>
                                                <th class="sort" data-sort="date">Initial State.</th>
                                                <th class="sort" data-sort="date">Status</th>
                                                <th class="sort" data-sort="date">Action</th>

                                            </tr>
                                        </thead>
                                        <tbody class="list form-check-all">

                                            <?php
                                            $sn = 0;
                                            foreach ($all_book_copies as $value):

                                                $sn++;
                                            ?>
                                                <tr>
                                                    <th scope="row">
                                                        <?= $sn ?>
                                                    </th>

                                                    <td><?= $value->book_copy_no ?></td>
                                                    <td><?= $value->comment ?></td>
                                                    <td><?php
                                                        if ($value->status == "lost") {
                                                            echo '<span class="badge bg-danger">Lost</span>';
                                                        } elseif ($value->status == "damaged") {
                                                            echo '<span class="badge bg-danger">Damaged</span>';
                                                        } elseif ($value->status == "borrowed") {
                                                            echo '<span class="badge bg-primary">Borrowed</span>';
                                                        } else {
                                                            echo '<span class="badge bg-secondary">Available</span>';
                                                        }

                                                        $value->status ?></td>
                                                    <td>
                                                        <div class="d-flex gap-2">
                                                            <div class="d-flex gap-2">
                                                                <a title="View Timeline" class="btn btn-sm btn-primary" href="index.php?page=book_copy_timeline&id=<?= $value->id ?>">
                                                                    <i class="fas fa-eye"></i>
                                                                </a>
                                                                <a title="Edit Book Copy" class="btn btn-sm btn-primary " href="index.php?page=edit_book_copy&id=<?= $value->id ?>"><i class="fas fa-pencil"></i> </a>

                                                                <button title="Delete Book Copy" onclick="deleteBookCopy('<?= $value->id ?>')" class="btn btn-sm btn-danger remove-item-btn"><i class="fas fa-trash"></i> </button>


                                                            </div>


                                                        </div>
                                                    </td>

                                                </tr>
                                            <?php endforeach; ?>
                                        </tbody>
                                    </table>

                                </div>


                            </div>
                        </div><!-- end card -->
                    </div>
                    <!-- end col -->
                </div>
                <!-- end col -->
            </div>
            <!-- end row -->



        </div>
    </div>


    <!-- Modal fadeInUp -->
    <div id="add_new_book_copy_modal" class="modal fade fadeInUp" tabindex="-1" aria-labelledby="fadeInUpModalLabel" aria-hidden="true" style="display: none;">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="fadeInUpModalLabel">Add New Book Copy</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="add_new_book_copy">
                        <input type="text" value="<?= $book_details->id ?>" name="book_id" hidden />
                        <div class="row gy-4">

                            <!--end col-->
                            <div class="col-xxl-3 col-md-12">
                                <div>
                                    <label for="labelInput" class="form-label">Book Copy Number </label>
                                    <input type="text" name="copy_number" placeholder="Book Copy Number" class="form-control">
                                </div>
                            </div>
                            <!--end col-->
                            <div class="col-xxl-3 col-md-12">
                                <div>
                                    <label for="placeholderInput" class="form-label">Comment</label>
                                    <textarea name="comment" class="form-control" placeholder="Book Copy Status Comment"></textarea>

                                </div>
                            </div>
                        </div>
                        <hr>
                        <div class="modal-footer mt-4">
                            <button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary ">Register</button>
                        </div>
                </div>
                </form>

            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <script>
        $('#add_new_book_copy').on('submit', function(e) {

            e.preventDefault();
            $.ajax({
                url: request() + '?file=books&action=add_new_book_copy',
                method: 'POST',
                data: new FormData(this),
                contentType: false,
                processData: false,
                cache: false,
                success: function(response) {
                    console.log(response);
                    if (response.status == 200) {
                        Swal.fire({
                            title: "Good job!",
                            text: response.message,
                            icon: "success",
                            showConfirmButton: true,
                        });
                        setTimeout(function() {
                            window.location.reload()
                        }, 2e3);

                    } else {
                        Swal.fire({
                            title: "Oops!",
                            text: response.message,
                            icon: "error",
                            cancelButtonClass: "btn btn-danger ml-2 mt-2",
                            confirmButtonColor: "#6c757d"
                        });
                    }
                }
            });
        });

        function deleteBookCopy(id) {
            // Show SweetAlert confirmation dialog
            Swal.fire({
                title: 'Are you sure?',
                text: "This action cannot be undone!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    // If confirmed, proceed with AJAX request
                    $.ajax({
                        url: request() + '?file=books&action=delete_book_copy',
                        method: 'POST',
                        data: {
                            id: id
                        },
                        success: function(data) {
                            console.log(data);
                            if (data.status == 200) {
                                iziToast.success({
                                    title: 'Info',
                                    message: data.message,
                                    position: 'topRight'
                                });
                                setTimeout(function() {
                                    location.reload();
                                }, 1000);
                            } else {
                                iziToast.error({
                                    title: 'Alert',
                                    message: data.message,
                                    position: 'topRight'
                                });
                            }
                        }
                    });
                }
            });
        }
    </script>