<?php
$all_book_copy_timelines = $db->where('book_copy_id', secure_data($_GET['id']))->get("borrowed_copies");
$book_copy_details = $db->where('id', secure_data($_GET['id']))->getOne('books');
$page_title = 'All Book Copy Timelines';


?>
<div class="main-content">


    <div class="page-content">
        <div class="container-fluid">

            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                        <h4 class="mb-sm-0"><?= $page_title ?></h4>

                        <div class="page-title-right">
                            <ol class="breadcrumb m-0">
                                <li class="breadcrumb-item"><a href="javascript: void(0);">Home</a></li>
                                <li class="breadcrumb-item active">Book Copy History</li>
                            </ol>
                        </div>

                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">

                        <div class="card-body">
                            <div class="listjs-table" id="customerList">

                                <div class="row g-4 mb-3">
                                    <div class="col-sm">
                                        <div class="d-flex justify-content-sm-end">
                                            <div class="search-box ms-2">
                                                <a data-bs-toggle="modal" data-bs-target="#filter_" type="button" class="btn btn-primary add-btn"><i class="ri-filter-line align-bottom me-1"></i> Filter By Category</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="table-responsive mt-3 mb-1">
                                    <table id="myTable" class="table table-bordered table-striped">
                                        <thead class="table-light">
                                            <tr>
                                                <th scope="col">
                                                    S/No.
                                                </th>
                                                <th class="sort" data-sort="date">Borrowed By.</th>
                                                <th class="sort" data-sort="date">Borrowed On.</th>
                                                <th class="sort" data-sort="date">Comment On Borrow</th>

                                                <th class="sort" data-sort="date">Returned On</th>
                                                <th class="sort" data-sort="date">Comment On return</th>

                                            </tr>
                                        </thead>
                                        <tbody class="list form-check-all">

                                            <?php
                                            $sn = 0;
                                            foreach ($all_book_copy_timelines as $value):
                                                $student_details = $db->where('id', $value->student_id)->getOne('users');
                                                $request_details = $db->where("id", $value->requesition_id)->getOne("borrow_requests");
                                                $class_details = $db->where("id", $student_details->class_id)->getOne("classes");

                                                $sn++;
                                            ?>
                                                <tr>
                                                    <th scope="row">
                                                        <?= $sn ?>
                                                    </th>
                                                    <td><?= $student_details->firstname . ' ' . $student_details->lastname . ' ( ' . $class_details->abbrev . ' )'  ?></td>
                                                    <td><?= date('d/m/Y', strtotime($value->date_created)) ?></td>
                                                    <td><?= $value->assign_comment ?></td>
                                                    <?php
                                                    if (empty($value->return_status)) { ?>
                                                        <td></td>
                                                        <td></td>
                                                        <?php } else {
                                                        if ($value->return_status == 'returned') { ?>
                                                            <td><?= date('d/m/Y', strtotime($value->returned_on)) ?></td>
                                                            <td><?= $value->return_comment ?></td>
                                                        <?php } else if ($value->return_status == 'lost') { ?>
                                                            <td> <span class="badge bg-danger">Book lost</span></td>
                                                            <td><?= $value->return_comment ?></td>

                                                        <?php  }
                                                        ?>
                                                    <?php }
                                                    ?>


                                                </tr>
                                            <?php endforeach; ?>
                                        </tbody>
                                    </table>

                                </div>


                            </div>
                        </div><!-- end card -->
                    </div>
                    <!-- end col -->
                </div>
                <!-- end col -->
            </div>
            <!-- end row -->



        </div>
    </div>


    <!-- Modal fadeInUp -->
    <div id="add_new_book_copy_modal" class="modal fade fadeInUp" tabindex="-1" aria-labelledby="fadeInUpModalLabel" aria-hidden="true" style="display: none;">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="fadeInUpModalLabel">Add New Book Copy</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="add_new_book_copy">
                        <input type="text" value="<?= $book_details->id ?>" name="book_id" hidden />
                        <div class="row gy-4">

                            <!--end col-->
                            <div class="col-xxl-3 col-md-12">
                                <div>
                                    <label for="labelInput" class="form-label">Book Copy Number </label>
                                    <input type="text" name="copy_number" placeholder="Book Copy Number" class="form-control">
                                </div>
                            </div>
                            <!--end col-->
                            <div class="col-xxl-3 col-md-12">
                                <div>
                                    <label for="placeholderInput" class="form-label">Comment</label>
                                    <textarea name="comment" class="form-control" placeholder="Book Copy Status Comment"></textarea>

                                </div>
                            </div>
                        </div>
                        <hr>
                        <div class="modal-footer mt-4">
                            <button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary ">Register</button>
                        </div>
                </div>
                </form>

            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <script>
        $('#add_new_book_copy').on('submit', function(e) {

            e.preventDefault();
            $.ajax({
                url: request() + '?file=books&action=add_new_book_copy',
                method: 'POST',
                data: new FormData(this),
                contentType: false,
                processData: false,
                cache: false,
                success: function(response) {
                    console.log(response);
                    if (response.status == 200) {
                        Swal.fire({
                            title: "Good job!",
                            text: response.message,
                            icon: "success",
                            showConfirmButton: true,
                        });
                        setTimeout(function() {
                            window.location.reload()
                        }, 2e3);

                    } else {
                        Swal.fire({
                            title: "Oops!",
                            text: response.message,
                            icon: "error",
                            cancelButtonClass: "btn btn-danger ml-2 mt-2",
                            confirmButtonColor: "#6c757d"
                        });
                    }
                }
            });
        });

        function deleteBookCopy(id) {
            // Show SweetAlert confirmation dialog
            Swal.fire({
                title: 'Are you sure?',
                text: "This action cannot be undone!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    // If confirmed, proceed with AJAX request
                    $.ajax({
                        url: request() + '?file=books&action=delete_book_copy',
                        method: 'POST',
                        data: {
                            id: id
                        },
                        success: function(data) {
                            console.log(data);
                            if (data.status == 200) {
                                iziToast.success({
                                    title: 'Info',
                                    message: data.message,
                                    position: 'topRight'
                                });
                                setTimeout(function() {
                                    location.reload();
                                }, 1000);
                            } else {
                                iziToast.error({
                                    title: 'Alert',
                                    message: data.message,
                                    position: 'topRight'
                                });
                            }
                        }
                    });
                }
            });
        }
    </script>