   <?php
    $borrowed_copy = $db->where("id", secure_data($_GET['id']))->getOne("borrowed_copies");
    $req_details = $db->where("id", $borrowed_copy->requesition_id)->getOne("borrow_requests");
    $book_details = $db->where("id", $req_details->book_id)->getOne("books");
    $student_details = $db->where('id', $req_details->student_id)->getOne('users');
    ?>
   <div class="main-content">


       <div class="page-content">
           <div class="container-fluid">

               <!-- start page title -->
               <div class="row">
                   <div class="col-12">
                       <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                           <h4 class="mb-sm-0">Transaction History</h4>

                           <div class="page-title-right">
                               <ol class="breadcrumb m-0">
                                   <li class="breadcrumb-item"><a href="javascript: void(0);">Home</a></li>
                                   <li class="breadcrumb-item active">Records</li>
                               </ol>
                           </div>

                       </div>
                   </div>
               </div>
               <div class="row">
                   <div class="col-12">

                       <div class="col-xxl-4">
                           <div class="card border-info shadow-lg">
                               <div class="card-header bg-info text-white">
                                   <h6 class="card-title mb-0 d-flex justify-content-between align-items-center">
                                       Borrowed Book Transaction History

                                   </h6>
                               </div>
                               <div class="card-body">
                                   <p><strong>Student Name : </strong><?= $student_details->firstname . ' ' . $student_details->lastname . ' ' . $student_details->othername ?></p>
                                   <p><strong>Borrowed Book:</strong> <?= $book_details->title . '<b> by </b>' . $db->where('id', $book_details->author_id)->getOne('book_authors')->names; ?> <br>
                                       <strong>ISBN:</strong> <?= $book_details->isbn; ?>
                                   </p>
                                   <p>
                                       <strong>Borrowing Reason : </strong><?= $req_details->reason; ?>
                                   </p>
                                   <p><strong>Borrowed Book Copy No.: </strong> <?= $db->where('id', $borrowed_copy->book_copy_id)->getOne('book_copies')->book_copy_no; ?></p>
                                   <p>
                                       <strong>Return Date:</strong> <?= date('d/m/Y', strtotime($req_details->return_date)); ?>
                                   </p>
                                   <hr>
                                   <?php if ($req_details->aprove_status == 1) { ?>
                                       <p><strong>Approval Status:</strong>
                                           <span class="badge bg-success">Approved</span><br><br>
                                           <strong>Approved On : </strong><?= date('d/m/Y', strtotime($req_details->date_approved)) ?>
                                       </p>


                                       <p>
                                       <?php } else {  ?>
                                           <strong>Approval Status:</strong><span class="badge bg-info">Pending</span>
                                       <?php } ?>
                                       <hr>
                                       <hr>
                                       <?php if ($borrowed_copy->return_status == 'returned') { ?>
                                       <p><strong>Return Status:</strong>
                                           <span class="badge bg-success">Returned</span><br><br>
                                           <strong>Return On : </strong><?= date('d/m/Y', strtotime($borrowed_copy->returned_on)) ?>
                                       </p>
                                       <p><strong>Comment :</strong><?= $borrowed_copy->return_comment; ?></p>


                                       <p>
                                       <?php } else if ($borrowed_copy->return_status == 'damaged') {
                                            echo '<strong>Return Date: </strong><span">' . date('d/m/Y', strtotime($req_details->return_date)) . '</span><br><br><strong>Return Status: </strong><span class="badge bg-danger"> Damaged</span>';
                                        } else if ($borrowed_copy->return_status == 'lost') {
                                            echo '<strong>Return Date: </strong><span">' . date('d/m/Y', strtotime($req_details->return_date)) . '</span><br><br><strong>Return Status: </strong><span class="badge bg-danger"> Lost</span>';
                                        } else { ?>
                                           <strong>Approval Status :</strong><span class="badge bg-info">Pending</span>
                                       <?php } ?>
                                       <hr>

                                       <div class="d-flex mt-3">
                                           <?php if ($global_var['user']['user_type'] != 'stud') {
                                                if ($req_details->aprove_status != 1) { ?>
                                                   <button class="btn btn-success m-1 approve"><i class="fas fa-check"></i> Approve</button>
                                                   <button class="btn btn-danger m-1"><i class="fas fa-times"></i> Reject</button>
                                                   <?php } else {
                                                    if (empty($borrowed_copy->return_status)) { ?>
                                                       <button data-bs-toggle="modal" data-bs-target="#confirm_return" class="btn btn-success m-1"><i class="fas fa-check"></i> Confirm Return</button>
                                                   <?php }
                                                }
                                            } else {
                                                if ($req_details->aprove_status != 1) { ?>
                                                   <button class="btn btn-warning m-1"><i class="fas fa-edit"></i> Edit</button>
                                                   <button class="btn btn-secondary m-1"><i class="fas fa-trash"></i> Delete</button>
                                           <?php  }
                                            } ?>
                                       </div>
                               </div>
                           </div>
                       </div><!-- end col -->
                   </div><!-- end row -->
               </div><!-- end col -->
           </div><!-- end row -->
       </div><!-- end col -->
   </div><!-- end row -->
   <!-- Add new Borrow request Modal -->
   <div id="confirm_return" class="modal fade fadeInUp" tabindex="-1" aria-labelledby="fadeInUpModalLabel" aria-hidden="true" style="display: none;">
       <div class="modal-dialog modal-dialog-centered">
           <div class="modal-content">
               <div class="modal-header">
                   <h5 class="modal-title" id="fadeInUpModalLabel">Confirm Book Return</h5>
                   <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
               </div>
               <div class="modal-body">
                   <form id="confirm_borrow_return">
                       <input type="text" name="book_id" value="<?= $req_details->book_id ?>" hidden />
                       <input type="text" name="return_copies" value="<?= $req_details->no_of_copies ?>" hidden />
                       <input type="text" name="id" value="<?= $req_details->id ?>" hidden />
                       <div class="row gy-4">


                           <!--end col-->


                           <div class="col-xxl-3 col-md-6 d-none">
                               <div>
                                   <label for="placeholderInput" class="form-label">No. Of Copies Returned</label>
                                   <input type="text" class="form-control" name="no_of_copies" placeholder="No. Of Copies returned">
                               </div>
                           </div>
                           <div class="col-xxl-3 col-md-12">
                               <div>
                                   <label for="placeholderInput" class="form-label">Return date</label>
                                   <input type="date" class="form-control" name="return_date">
                               </div>
                           </div>
                           <div class="col-xxl-3 col-md-12">
                               <div>
                                   <label for="placeholderInput" class="form-label">Comment</label>
                                   <textarea placeholder="Enter Comment here.." class="form-control" name="comment"></textarea>

                               </div>
                           </div>
                           <!--end col-->


                       </div>
                       <hr>
                       <div class="modal-footer mt-4">
                           <button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
                           <button type="submit" class="btn btn-primary">Confirm</button>
                       </div>
               </div>
               </form>

           </div><!-- /.modal-content -->
       </div><!-- /.modal-dialog -->
   </div><!-- /.modal -->
   <script>
       $(document).ready(function() {
           // Approve Button Click
           $(document).on("click", ".approve", function() {
               var el = this;
               var req_id = '<?= secure_data($_GET['id']) ?>';
               var no_of_copies = '<?= $req_details->no_of_copies ?>';
               var book_id = '<?= $req_details->book_id ?>';
               Swal.fire({
                   title: 'Are you sure?',
                   text: "You want to approve this borrow Request?",
                   icon: 'warning',
                   showCancelButton: true,
                   confirmButtonColor: '#3085d6',
                   cancelButtonColor: '#d33',
                   confirmButtonText: 'Yes, approve it!'
               }).then((result) => {
                   if (result.isConfirmed) {
                       // AJAX Request
                       $.ajax({
                           url: request() + '?file=borrow&action=approve_borrow_request',
                           type: 'POST',
                           data: {
                               id: req_id,
                               no_of_copies: no_of_copies,
                               book_id: book_id
                           },
                           success: function(response) {
                               console.log(response);
                               if (response.status == 200) {
                                   Swal.fire({
                                       title: "Good job!",
                                       text: response.message,
                                       icon: "success",
                                       showConfirmButton: false,
                                   });
                                   setTimeout(function() {
                                       window.location.href = response.url;
                                   }, 2e3);
                               } else {
                                   Swal.fire({
                                       title: "Oops!",
                                       text: response.message,
                                       icon: "error",
                                       cancelButtonClass: "btn btn-danger ml-2 mt-2",
                                       confirmButtonColor: "#6c757d"
                                   });
                               }
                           }
                       });
                   }
               });
           })
       })
       $('#confirm_borrow_return').on('submit', function(e) {

           e.preventDefault();
           $.ajax({
               url: request() + '?file=borrow&action=confirm_return',
               method: 'POST',
               data: new FormData(this),
               contentType: false,
               processData: false,
               cache: false,
               success: function(response) {
                   console.log(response);
                   if (response.status == 200) {
                       Swal.fire({
                           title: "Good job!",
                           text: response.message,
                           icon: "success",
                           showConfirmButton: true,
                       });
                       setTimeout(function() {
                           window.location.href = response.url;
                       }, 2e3);

                   } else {
                       Swal.fire({
                           title: "Oops!",
                           text: response.message,
                           icon: "error",
                           cancelButtonClass: "btn btn-danger ml-2 mt-2",
                           confirmButtonColor: "#6c757d"
                       });
                   }
               }
           });
       });
   </script>