   <?php
    $book_details = $db->where("id", secure_data($_GET['id']))->getOne("books");
    $category_details = $db->where("id", $book_details->category_id)->getOne("categories");
    ?>
   <div class="main-content">


       <div class="page-content">
           <div class="container-fluid">

               <!-- start page title -->
               <div class="row">
                   <div class="col-12">
                       <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                           <h4 class="mb-sm-0">Edit Book Details</h4>

                           <div class="page-title-right">
                               <ol class="breadcrumb m-0">
                                   <li class="breadcrumb-item"><a href="javascript: void(0);">Home</a></li>
                                   <li class="breadcrumb-item active">Edit Book</li>
                               </ol>
                           </div>

                       </div>
                   </div>
               </div>
               <div class="row">
                   <div class="col-12">

                       <div class="col-xxl-4">
                           <div class="card border-info shadow-lg">
                               <div class="card-header bg-info text-white">
                                   <h6 class="card-title mb-0 d-flex justify-content-between align-items-center">
                                       Edit Book

                                   </h6>
                               </div>
                               <div class="card-body">
                                   <form id="edit_book">
                                       <input type="text" name="book_id" value="<?= $book_details->id ?>" Hidden>
                                       <div class="row">

                                           <div class="row">

                                               <div class="col-xxl-3 col-md-12">
                                                   <div>
                                                       <label for="basiInput" class="form-label">Book Category</label>
                                                       <select name="category_id" class="form-control selectpicker" data-live-search="true">
                                                           <option value="<?= $book_details->category_id ?>"><?= $db->where("id", $book_details->category_id)->getOne("categories")->name ?></option>
                                                           <?php foreach ($db->get("categories") as $value) { ?>
                                                               <option value="<?= $value->id ?>"><?= $value->name ?></option>
                                                           <?php } ?>
                                                       </select>

                                                   </div>
                                               </div>


                                               <!--end col-->
                                               <div class="col-xxl-3 col-md-12">
                                                   <div>
                                                       <label for="labelInput" class="form-label">Book Title </label>
                                                       <input type="text" value="<?= $book_details->title ?>" name="title" class="form-control">
                                                   </div>
                                               </div>
                                               <div class="col-xxl-3 col-md-12" id="selectAuthorDiv">
                                                   <div>
                                                       <label for="basiInput" class="form-label">Book Author</label>
                                                       <select id="authorSelect" name="author_id" class="form-control selectpicker" data-live-search="true">

                                                           <option value="<?= $book_details->author_id ?>"><?= $db->where("id", $book_details->author_id)->getOne("book_authors")->names ?></option>
                                                           <?php foreach ($db->get("book_authors") as $value) { ?>
                                                               <option value="<?= $value->id ?>"><?= $value->names ?></option>
                                                           <?php } ?>
                                                       </select>
                                                   </div>
                                               </div>

                                               <div class="col-xxl-3 col-md-12">
                                                   <div>
                                                       <label for="registerAuthor" class="form-label">Register New Book Author</label>
                                                       <input type="checkbox" name="new_author" value="1" id="registerAuthor" />
                                                   </div>
                                               </div>

                                               <!-- Book Author Name Input (Initially Hidden) -->
                                               <div class="col-xxl-3 col-md-12 d-none" id="newAuthorDiv">
                                                   <div>
                                                       <label for="placeholderInput" class="form-label">Book Author Name</label>
                                                       <input type="text" class="form-control" name="author_names" placeholder="Book Author">
                                                   </div>
                                               </div>


                                               <div class="col-xxl-3 col-md-12">
                                                   <div>
                                                       <label for="placeholderInput" class="form-label">ISBN</label>
                                                       <input type="text" class="form-control" value="<?= $book_details->isbn ?>" name="isbn" placeholder="ISBN">
                                                   </div>
                                               </div>
                                               <div class="col-xxl-3 col-md-6">
                                                   <div>
                                                       <label for="placeholderInput" class="form-label">Year of Publication</label>
                                                       <input type="text" class="form-control" value="<?= $book_details->publication_year ?>" name="publication_year" placeholder="Year of Publication">
                                                   </div>
                                               </div>
                                               <div class="col-xxl-3 col-md-6">
                                                   <div>
                                                       <label for="placeholderInput" class="form-label">No. Of Initial Copies</label>
                                                       <input type="text" class="form-control" value="<?= $db->where("book_id", $book_details->id)->getOne("current_books")->no_of_copies ?>" name="no_of_copies" placeholder="No. Of Book Copies Available">
                                                   </div>
                                               </div>
                                               <!--end col-->


                                           </div>


                                       </div>
                                       <hr>

                                       <div class="d-flex mt-3 align-items-center justify-content-center ">
                                           <button type="submit" class="btn btn-warning m-1"><i class="fas fa-edit"></i> Edit Book Details</button>
                                       </div>
                                   </form>
                               </div>
                           </div>
                       </div><!-- end col -->
                   </div><!-- end row -->
               </div><!-- end col -->
           </div><!-- end row -->
       </div><!-- end col -->
   </div><!-- end row -->
   <script>
       $('#edit_book').on('submit', function(e) {

           e.preventDefault();
           $.ajax({
               url: request() + '?file=books&action=edit_book',
               method: 'POST',
               data: new FormData(this),
               contentType: false,
               processData: false,
               cache: false,
               success: function(response) {
                   console.log(response);
                   if (response.status == 200) {
                       Swal.fire({
                           title: "Good job!",
                           text: response.message,
                           icon: "success",
                           showConfirmButton: true,
                       });
                       setTimeout(function() {
                           window.location.reload()
                       }, 2e3);

                   } else {
                       Swal.fire({
                           title: "Oops!",
                           text: response.message,
                           icon: "error",
                           cancelButtonClass: "btn btn-danger ml-2 mt-2",
                           confirmButtonColor: "#6c757d"
                       });
                   }
               }
           });
       });
       document.getElementById('registerAuthor').addEventListener('change', function() {
           let newAuthorDiv = document.getElementById('newAuthorDiv');
           let selectAuthorDiv = document.getElementById('selectAuthorDiv');
           if (this.checked) {
               newAuthorDiv.classList.remove('d-none'); // Show new author input field
               selectAuthorDiv.classList.add('d-none'); // Hide Select Author field
           } else {
               newAuthorDiv.classList.add('d-none'); // Hide input field
               selectAuthorDiv.classList.remove('d-none'); // Show Select Author field
           }
       });
   </script>