   <?php
    $req_details = $db->where("id", secure_data($_GET['id']))->getOne("borrow_requests");
    $book_details = $db->where("id", $req_details->book_id)->getOne("books");
    $student_details = $db->where('id', $req_details->student_id)->getOne('users');
    ?>
   <div class="main-content">


       <div class="page-content">
           <div class="container-fluid">

               <!-- start page title -->
               <div class="row">
                   <div class="col-12">
                       <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                           <h4 class="mb-sm-0">Edit Borrow Requisition</h4>

                           <div class="page-title-right">
                               <ol class="breadcrumb m-0">
                                   <li class="breadcrumb-item"><a href="javascript: void(0);">Home</a></li>
                                   <li class="breadcrumb-item active">Edit </li>
                               </ol>
                           </div>

                       </div>
                   </div>
               </div>
               <div class="row">
                   <div class="col-12">

                       <div class="col-xxl-4">
                           <div class="card border-info shadow-lg">
                               <div class="card-header bg-info text-white">
                                   <h6 class="card-title mb-0 d-flex justify-content-between align-items-center">
                                       Edit Borrow Request

                                   </h6>
                               </div>
                               <div class="card-body">
                                   <form id="edit_class">
                                       <input type="text" name="id" value="<?= $req_details->id ?>" Hidden>


                                       <div class="row gy-4">

                                           <div class="col-xxl-3 col-md-12">
                                               <div>
                                                   <label for="basiInput" class="form-label">Book</label>
                                                   <select name="book_id" class="form-control selectpicker " data-live-search="true">
                                                       <option value="<?= $book_details->id ?>"><?= $book_details->title . ' : By ' . $book_details->author ?></option>
                                                       <?php foreach ($db->get("books") as $value) { ?>
                                                           <option value="<?= $value->id ?>"><?= $value->title . ' : By ' . $value->author ?></option>
                                                       <?php } ?>
                                                   </select>
                                               </div>
                                           </div>
                                           <!--end col-->
                                           <div class="col-xxl-3 col-md-12">
                                               <div>
                                                   <label for="placeholderInput" class="form-label">Reason</label>
                                                   <textarea placeholder="Enter Borrowing reason here.." class="form-control" name="reason"><?= $req_details->reason ?></textarea>

                                               </div>
                                           </div>

                                           <div class="col-xxl-3 col-md-6">
                                               <div>
                                                   <label for="placeholderInput" class="form-label">No. Of Copies to be Borrowed</label>
                                                   <input type="text" class="form-control" name="no_of_copies" value="<?= $req_details->no_of_copies ?>" placeholder="No. Of Book Copies Available">
                                               </div>
                                           </div>
                                           <div class="col-xxl-3 col-md-6">
                                               <div>
                                                   <label for="placeholderInput" class="form-label">Return date</label>
                                                   <input type="date" value="<?= $req_details->return_date ?>" class="form-control" name="return_date">
                                               </div>
                                           </div>
                                           <!--end col-->


                                       </div>
                                       <hr>

                                       <div class="d-flex mt-3 align-items-center justify-content-center ">
                                           <button type="submit" class="btn btn-primary m-1"><i class="fas fa-edit"></i> Edit Request Details</button>
                                       </div>
                                   </form>
                               </div>
                           </div>
                       </div><!-- end col -->
                   </div><!-- end row -->
               </div><!-- end col -->
           </div><!-- end row -->
       </div><!-- end col -->
   </div><!-- end row -->
   <script>
       $('#edit_class').on('submit', function(e) {

           e.preventDefault();
           $.ajax({
               url: request() + '?file=borrow&action=edit_request',
               method: 'POST',
               data: new FormData(this),
               contentType: false,
               processData: false,
               cache: false,
               success: function(response) {
                   console.log(response);
                   if (response.status == 200) {
                       Swal.fire({
                           title: "Good job!",
                           text: response.message,
                           icon: "success",
                           showConfirmButton: true,
                       });
                       setTimeout(function() {
                           window.location.reload()
                       }, 2e3);

                   } else {
                       Swal.fire({
                           title: "Oops!",
                           text: response.message,
                           icon: "error",
                           cancelButtonClass: "btn btn-danger ml-2 mt-2",
                           confirmButtonColor: "#6c757d"
                       });
                   }
               }
           });
       });

       function deleteItem(id, no_of_copies, book_id) {
           // Show SweetAlert confirmation dialog
           Swal.fire({
               title: 'Are you sure?',
               text: "This action cannot be undone!",
               icon: 'warning',
               showCancelButton: true,
               confirmButtonColor: '#3085d6',
               cancelButtonColor: '#d33',
               confirmButtonText: 'Yes, delete it!'
           }).then((result) => {
               if (result.isConfirmed) {
                   // If confirmed, proceed with AJAX request
                   $.ajax({
                       url: request() + '?file=books&action=delete_category',
                       method: 'POST',
                       data: {
                           id: id,
                           book_id: book_id,
                           no_of_copies: no_of_copies,
                       },
                       success: function(data) {
                           console.log(data);
                           if (data.status == 200) {
                               iziToast.success({
                                   title: 'Info',
                                   message: data.message,
                                   position: 'topRight'
                               });
                               setTimeout(function() {
                                   location.reload();
                               }, 1000);
                           } else {
                               iziToast.error({
                                   title: 'Alert',
                                   message: data.message,
                                   position: 'topRight'
                               });
                           }
                       }
                   });
               }
           });
       }
   </script>