   
   <?php 
   $book_details = $db->where("id", __secure($_GET['id']))->getOne("books");
   $category_details = $db->where("id", $book_details->category_id)->getOne("categories");
   ?>
   <div class="main-content">


<div class="page-content">
    <div class="container-fluid">

        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                    <h4 class="mb-sm-0">Edit Book Details</h4>

                    <div class="page-title-right">
                        <ol class="breadcrumb m-0">
                            <li class="breadcrumb-item"><a href="javascript: void(0);">Home</a></li>
                            <li class="breadcrumb-item active">Edit Book</li>
                        </ol>
                    </div>

                </div>
            </div>
        </div>
   <div class="row">
                        <div class="col-12">
                            
                            <div class="col-xxl-4">
                                 <div class="card border-info shadow-lg">
    <div class="card-header bg-info text-white">
        <h6 class="card-title mb-0 d-flex justify-content-between align-items-center">
           Edit Book
            
        </h6>
    </div>
    <div class="card-body">
        <form id="edit_book">
            <input type="text" name="book_id" value="<?= $book_details->id ?>" Hidden>
        <div class="row">

            <div class="col-xxl-3 col-md-12">
                                                <div>
                                                    <label for="basiInput" class="form-label">Book Category</label>
                                                    <select name="category_id" class="form-control">
                                                        <option value="<?= $category_details->id ?>"><?= $category_details->name ?></option>
                                                    <?php foreach ($db->get("categories") as $value) { ?>
                                                        <option value="<?= $value->id ?>"><?= $value->name ?></option>
                                                    <?php } ?>
                                                    </select>
                                                </div>
                                            </div>
                                            <!--end col-->
                                            <div class="col-xxl-3 col-md-12">
                                                <div>
                                                    <label for="labelInput" class="form-label">Book Title </label>
                                                    <input type="text" value="<?= $book_details->title ?>"  name="title" class="form-control">
                                                </div>
                                            </div>
                                            <!--end col-->
                                            <div class="col-xxl-3 col-md-12">
                                                <div>
                                                    <label for="placeholderInput" class="form-label">Book Aurthor</label>
                                                    <input type="text" value="<?= $book_details->author ?>" class="form-control"  name="aurthor" placeholder="Book Aurthor">
                                                </div>
                                            </div>
                                             <div class="col-xxl-3 col-md-12">
                                                <div>
                                                    <label for="placeholderInput" class="form-label">ISBN</label>
                                                    <input type="text" value="<?= $book_details->isbn ?>" class="form-control"  name="isbn" placeholder="ISBN">
                                                </div>
                                            </div>
                                       
            
        </div>
        <hr>

      <div class="d-flex mt-3 align-items-center justify-content-center ">
    <button type="submit" class="btn btn-warning m-1"><i class="fas fa-edit"></i> Edit Book Details</button>
</div>
</form>
    </div>
</div>
</div><!-- end col -->
    </div><!-- end row -->
                        </div><!-- end col -->
                    </div><!-- end row -->
                     </div><!-- end col -->
                    </div><!-- end row -->
<script>
   $('#edit_book').on('submit',function(e){
      
            e.preventDefault();
            $.ajax({
                url: request()+'?f=books&s=edit_book',
                method: 'POST',
                data: new FormData(this),
                contentType: false,
                processData: false,
                cache: false,
                success: function(response){
                    console.log(response);
                     if (response.status == 200) {
                    Swal.fire({
                            title: "Good job!",
                            text: response.message,
                            icon: "success",
                            showConfirmButton: true,
                        });
                        setTimeout(function () {
                            window.location.reload()
                        }, 2e3);

                } else {
                    Swal.fire({
                        title: "Oops!",
                        text: response.message,
                        icon: "error",
                        cancelButtonClass: "btn btn-danger ml-2 mt-2",
                        confirmButtonColor: "#6c757d"
                    });
                }
                }
            });
        });
</script>