<?php
$purchases = $db->orderBy('id', 'DESC')->get('purchases');
?>
<div class="main-content">


    <div class="page-content">
        <div class="container-fluid">

            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                        <h4 class="mb-sm-0">Book Inventory update</h4>

                        <div class="page-title-right">
                            <ol class="breadcrumb m-0">
                                <li class="breadcrumb-item"><a href="javascript: void(0);">Home</a></li>
                                <li class="breadcrumb-item active">Inventory Update</li>
                            </ol>
                        </div>

                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">

                        <div class="card-body">
                            <div class="listjs-table" id="customerList">
                                <div class="row g-4 mb-3">
                                    <div class="col-sm-auto">
                                        <div>
                                            <a data-bs-toggle="modal" data-bs-target="#new_nventory" type="button" class="btn btn-success add-btn"><i class="ri-add-line align-bottom me-1"></i> Add New Acquired/Purchased Books</a>

                                        </div>
                                    </div>
                                    <div class="col-sm-auto">
                                        <div>


                                        </div>
                                    </div>
                                    <div class="col-sm">
                                        <div class="d-flex justify-content-sm-end">
                                            <div class="search-box ms-2">
                                                <a href="" type="button" class="btn btn-primary add-btn"><i class="ri-add-line align-bottom me-1"></i> Filter Books</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="table-responsive mt-3 mb-1">
                                    <table id="myTable" class="table table-bordered table-striped">
                                        <thead class="table-light">
                                            <tr>
                                                <th scope="col">
                                                    S/No.
                                                </th>
                                                <th class="sort" data-sort="title">Title</th>
                                                <th class="sort" data-sort="description">Category</th>
                                                <th class="sort" data-sort="date">ISBN</th>
                                                <th class="sort" data-sort="date">Copies Purchased</th>
                                                <th class="sort" data-sort="date">Registered On</th>
                                                <th class="sort" data-sort="date">Registered By</th>
                                                <th class="sort" data-sort="action">Action</th>
                                            </tr>
                                        </thead>
                                        <tbody class="list form-check-all">

                                            <?php
                                            $sn = 0;
                                            foreach ($purchases as $value):
                                                $book_details = $db->where("id", $value->book_id)->getOne("books");


                                                $sn++;
                                            ?>
                                                <tr>
                                                    <th scope="row">
                                                        <?= $sn ?>
                                                    </th>
                                                    <td><?= $book_details->title ?></td>
                                                    <td class="title"><?= $db->where("id", $book_details->category_id)->getOne("categories")->name ?></td>
                                                    <td class="description"><?= $book_details->isbn ?></td>
                                                    <td><?= $value->no_of_copies ?></td>
                                                    <td class="date"><?= date('d/m/Y', strtotime($value->date_created)) ?></td>
                                                    <td><?= $db->where('id', $value->created_by)->getOne('users')->firstname ?></td>


                                                    <td>
                                                        <div class="d-flex gap-2">
                                                            <a class="btn btn-sm btn-success " href="index.php?page=edit_purchases&id=<?= $value->id ?>"><i class="fas fa-edit "></i> Edit</a>

                                                            <button onclick="deleteItem('<?= $value->id ?>', '<?= $value->no_of_copies ?>', '<?= $value->book_id ?>')" class="btn btn-sm btn-danger"><i class="fas fa-trash"></i> delete</button>

                                                        </div>
                                                    </td>
                                                </tr>
                                            <?php endforeach; ?>
                                        </tbody>
                                    </table>

                                </div>


                            </div>
                        </div><!-- end card -->
                    </div>
                    <!-- end col -->
                </div>
                <!-- end col -->
            </div>
            <!-- end row -->



        </div>
    </div>
    <!-- Add new Book Modal -->
    <div id="new_nventory" class="modal fade fadeInUp" tabindex="-1" aria-labelledby="fadeInUpModalLabel" aria-hidden="true" style="display: none;">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="fadeInUpModalLabel">Add Book Inventory</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="add_inventory">
                        <div class="row gy-4">

                            <div class="col-xxl-3 col-md-12">
                                <div>
                                    <label for="basiInput" class="form-label">Select Book</label>
                                    <select name="book_id" class="form-control selectpicker" data-live-search="true">
                                        <option value="">--Select Book--</option>
                                        <?php foreach ($db->get("books") as $value) { ?>
                                            <option value="<?= $value->id ?>"><?= $value->title . '. By : ' . $value->author ?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                            </div>
                            <!--end col-->


                            <!--end col-->


                            <div class="col-xxl-3 col-md-12">
                                <div>
                                    <label for="placeholderInput" class="form-label">No. Of Copies Acquired / Purchased</label>
                                    <input type="text" class="form-control" name="no_of_copies" placeholder="No. Of Book Copies ">
                                </div>
                            </div>
                            <!--end col-->


                        </div>
                        <hr>
                        <div class="modal-footer mt-4">
                            <button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary ">Update Inventory</button>
                        </div>
                </div>
                </form>

            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <!-- Add new Borrow request Modal -->

    <script type="text/javascript">
        function deleteItem(id, no_of_copies, book_id) {
            // Show SweetAlert confirmation dialog
            Swal.fire({
                title: 'Are you sure?',
                text: "This action cannot be undone!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    // If confirmed, proceed with AJAX request
                    $.ajax({
                        url: request() + '?file=purchases&action=delete_purchase',
                        method: 'POST',
                        data: {
                            id: id,
                            book_id: book_id,
                            no_of_copies: no_of_copies,
                        },
                        success: function(data) {
                            console.log(data);
                            if (data.status == 200) {
                                iziToast.success({
                                    title: 'Info',
                                    message: data.message,
                                    position: 'topRight'
                                });
                                setTimeout(function() {
                                    location.reload();
                                }, 1000);
                            } else {
                                iziToast.error({
                                    title: 'Alert',
                                    message: data.message,
                                    position: 'topRight'
                                });
                            }
                        }
                    });
                }
            });
        }
        $('#add_inventory').on('submit', function(e) {

            e.preventDefault();
            $.ajax({
                url: request() + '?file=purchases&action=update_inventory',
                method: 'POST',
                data: new FormData(this),
                contentType: false,
                processData: false,
                cache: false,
                success: function(response) {
                    console.log(response);
                    if (response.status == 200) {
                        Swal.fire({
                            title: "Good job!",
                            text: response.message,
                            icon: "success",
                            showConfirmButton: true,
                        });
                        setTimeout(function() {
                            window.location.href = response.url;
                        }, 2e3);

                    } else {
                        Swal.fire({
                            title: "Oops!",
                            text: response.message,
                            icon: "error",
                            cancelButtonClass: "btn btn-danger ml-2 mt-2",
                            confirmButtonColor: "#6c757d"
                        });
                    }
                }
            });
        });
    </script>