<?php
$first_day_of_month = date('Y-m-01');
$page_title = "Lost Books from " . date('d/m/Y', strtotime($first_day_of_month)) . " to today";

$lost_books = $db->orderBy('id', 'DESC')->where('date_created', $first_day_of_month, '>')->get('lost_books');
if ($global_var['user']['user_type'] == 'stud') {
    $lost_books = $db->orderBy('id', 'DESC')->where('student_id', $global_var['user']['id'])->where('date_created', $first_day_of_month, '>')->get('lost_books');
}
if (isset($_GET['start_date']) && isset($_GET['end_date'])) {
    $lost_books = $db->where('date_created', secure_data($_GET['start_date']), '>=')
        ->where('date_created', secure_data($_GET['end_date']), '<=')
        ->orderBy('id', 'DESC')
        ->get('lost_books');
    if ($global_var['user']['user_type'] == 'stud') {
        $lost_books = $db->where('student_id', $global_var['user']['id'])->where('date_created', secure_data($_GET['start_date']), '>=')
            ->where('date_created', secure_data($_GET['end_date']), '<=')
            ->orderBy('id', 'DESC')
            ->where('student_id', $global_var['user']['id'])
            ->get('lost_books');
    }
    $page_title = 'Lost Books FROM ' . date('d/m/Y', strtotime($_GET['start_date'])) . ' TO ' . date('d/m/Y', strtotime($_GET['end_date']));
}

?>
<div class="main-content">


    <div class="page-content">
        <div class="container-fluid">

            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                        <h4 class="mb-sm-0"><?= $page_title; ?></h4>

                        <div class="page-title-right">
                            <ol class="breadcrumb m-0">
                                <li class="breadcrumb-item"><a href="javascript: void(0);">Home</a></li>
                                <li class="breadcrumb-item active">Borrowed Books</li>
                            </ol>
                        </div>

                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">

                        <div class="card-body">
                            <div class="listjs-table" id="customerList">
                                <div class="row g-4 mb-3">

                                    <div class="col-sm">
                                        <div class="d-flex justify-content-sm-end">
                                            <div class="search-box ms-2">
                                                <a data-bs-toggle="modal" data-bs-target="#filter_by_date" type="button" class="btn btn-primary add-btn"><i class="ri-filter-line align-bottom me-1"></i> Filter Lost Books By Date</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>


                                <div class="table-responsive mt-3 mb-1">
                                    <?php if ($global_var['user']['user_type'] != 'stud') { ?>
                                        <table id="myTable" class="table table-bordered table-striped">
                                            <thead class="table-light">
                                                <tr>
                                                    <th scope="col">
                                                        S/No.
                                                    </th>
                                                    <th class="sort" data-sort="date">Lost Book</th>
                                                    <th class="sort" data-sort="date">Copies</th>
                                                    <th class="sort" data-sort="title">Student Name</th>
                                                    <th class="sort" data-sort="description">Class</th>
                                                    <th class="sort" data-sort="date">Comment</th>

                                                    <th class="sort" data-sort="action">Action</th>
                                                </tr>
                                            </thead>
                                            <tbody class="list form-check-all">

                                                <?php
                                                $sn = 0;
                                                foreach ($lost_books as $value):
                                                    $book_details = $db->where("id", $value->book_id)->getOne("books");
                                                    $student_details = $db->where('id', $value->student_id)->getOne('users');

                                                    $sn++;
                                                ?>
                                                    <tr>
                                                        <th scope="row">
                                                            <?= $sn ?>
                                                        </th>
                                                        <td><?= $book_details->title . ' ' . $book_details->author ?></td>
                                                        <td><?= $value->no_of_copies ?></td>
                                                        <td><?= $student_details->firstname . ' ' . $student_details->lastname ?></td>
                                                        <td><?= $db->where('id', $student_details->class_id)->getOne('classes')->abbrev ?></td>
                                                        <td><?= $value->comment ?></td>

                                                        <td>
                                                            <a title='View Details' href="index.php?page=borrow_history&id=<?= $value->requisition_id ?>" class="btn btn-sm btn-success " href=""><i class="fas fa-eye"></i> </a>
                                                        </td>
                                                    </tr>
                                                <?php endforeach; ?>
                                            </tbody>
                                        </table>
                                    <?php } else { ?>
                                        <table id="myTable" class="table table-bordered table-striped">
                                            <thead class="table-light">
                                                <tr>
                                                    <th scope="col">
                                                        S/No.
                                                    </th>
                                                    <th class="sort" data-sort="date">Lost Book</th>
                                                    <th class="sort" data-sort="date">Copies</th>
                                                    <th class="sort" data-sort="title">Student Name</th>
                                                    <th class="sort" data-sort="description">Class</th>
                                                    <th class="sort" data-sort="date">Comment</th>

                                                    <th class="sort" data-sort="action">Action</th>
                                                </tr>
                                            </thead>
                                            <tbody class="list form-check-all">

                                                <?php
                                                $sn = 0;
                                                foreach ($lost_books as $value):
                                                    $book_details = $db->where("id", $value->book_id)->getOne("books");
                                                    $student_details = $db->where('id', $value->student_id)->getOne('users');

                                                    $sn++;
                                                ?>
                                                    <tr>
                                                        <th scope="row">
                                                            <?= $sn ?>
                                                        </th>
                                                        <td><?= $book_details->title . ' ' . $book_details->author ?></td>
                                                        <td><?= $value->no_of_copies ?></td>
                                                        <td><?= $student_details->firstname . ' ' . $student_details->lastname ?></td>
                                                        <td><?= $db->where('id', $student_details->class_id)->getOne('classes')->abbrev ?></td>
                                                        <td><?= $value->comment ?></td>

                                                        <td>
                                                            <a title='View Details' href="index.php?page=borrow_history&id=<?= $value->requisition_id ?>" class="btn btn-sm btn-success " href=""><i class="fas fa-eye"></i> </a>
                                                        </td>
                                                    </tr>
                                                <?php endforeach; ?>
                                            </tbody>
                                        </table>
                                    <?php } ?>

                                </div>

                            </div>
                        </div><!-- end card -->
                    </div>
                    <!-- end col -->
                </div>
                <!-- end col -->
            </div>
            <!-- end row -->



        </div>
    </div>