<?php
$most_borrowed_books = $db
    ->where('aprove_status', 1)
    ->groupBy('student_id')
    ->orderBy('total_borrowed', 'DESC')
    ->get('borrow_requests', null, ['student_id', 'SUM(no_of_copies) as total_borrowed']);


$page_title = 'Most Borrowing Students';

?>


<div class="main-content">


    <div class="page-content">
        <div class="container-fluid">

            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                        <h4 class="mb-sm-0"><?= $page_title ?></h4>

                        <div class="page-title-right">
                            <ol class="breadcrumb m-0">
                                <li class="breadcrumb-item"><a href="javascript: void(0);">Home</a></li>
                                <li class="breadcrumb-item active">Most Borrowed</li>
                            </ol>
                        </div>

                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">

                        <div class="card-body">
                            <div class="listjs-table" id="customerList">
                                <div class="row g-4 mb-3">

                                    <div class="col-sm-auto">
                                        <div>


                                        </div>
                                    </div>

                                </div>

                                <div class="table-responsive mt-3 mb-1">
                                    <table id="myTable" class="table table-bordered table-striped">
                                        <thead class="table-light">
                                            <tr>
                                                <th scope="col">
                                                    S/No.
                                                </th>
                                                <th>Image</th>
                                                <th class="sort" data-sort="title">Student Name</th>
                                                <th class="sort" data-sort="title">Class</th>


                                                <th class="sort" data-sort="date">Copies Borrowed</th>

                                            </tr>
                                        </thead>
                                        <tbody class="list form-check-all">

                                            <?php
                                            $sn = 0;
                                            foreach ($most_borrowed_books as $value):
                                                $student_details = $db->where("id", $value->student_id)->getOne("users");
                                                $user_image = (empty($student_details->photo)) ? '/layout/assets/images/users/avatar-10.jpg' : $student_details->photo;


                                                $sn++;
                                            ?>
                                                <tr>
                                                    <th scope="row">
                                                        <?= $sn ?>
                                                    </th>
                                                    <td>

                                                        <div class="avatar-xs">
                                                            <img src="<?= $global_var['site_url'] . $user_image ?>" alt="" class="img-fluid rounded-circle candidate-img">
                                                        </div>

                                                    </td>
                                                    <td><?= $student_details->firstname . ' ' . $student_details->lastname  ?></td>
                                                    <td><?= $db->where('id', $student_details->class_id)->getOne('classes')->abbrev ?></td>

                                                    <td><?= $value->total_borrowed ?></td>

                                                </tr>
                                            <?php endforeach; ?>
                                        </tbody>
                                    </table>

                                </div>
                            </div>
                        </div><!-- end card -->
                    </div>
                    <!-- end col -->
                </div>
                <!-- end col -->
            </div>
            <!-- end row -->



        </div>
    </div>


    <script type="text/javascript">
        function deleteItem(id) {
            // Show SweetAlert confirmation dialog
            Swal.fire({
                title: 'Are you sure?',
                text: "This action cannot be undone!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    // If confirmed, proceed with AJAX request
                    $.ajax({
                        url: request() + '?file=books&action=delete',
                        method: 'POST',
                        data: {
                            id: id
                        },
                        success: function(data) {
                            console.log(data);
                            if (data.status == 200) {
                                iziToast.success({
                                    title: 'Info',
                                    message: data.message,
                                    position: 'topRight'
                                });
                                setTimeout(function() {
                                    location.reload();
                                }, 1000);
                            } else {
                                iziToast.error({
                                    title: 'Alert',
                                    message: data.message,
                                    position: 'topRight'
                                });
                            }
                        }
                    });
                }
            });
        }
        $('#filter_book').on('submit', function(e) {

            e.preventDefault();
            $.ajax({
                url: request() + '?file=books&action=filter_by_category',
                method: 'POST',
                data: new FormData(this),
                contentType: false,
                processData: false,
                cache: false,
                success: function(response) {
                    console.log(response);
                    if (response.status == 200) {
                        Swal.fire({
                            title: "Good job!",
                            text: response.message,
                            icon: "success",
                            showConfirmButton: true,
                        });
                        setTimeout(function() {
                            window.location.href = response.url;
                        }, 2e3);

                    } else {
                        Swal.fire({
                            title: "Oops!",
                            text: response.message,
                            icon: "error",
                            cancelButtonClass: "btn btn-danger ml-2 mt-2",
                            confirmButtonColor: "#6c757d"
                        });
                    }
                }
            });
        });
    </script>