    <!-- auth-page wrapper -->
    <!-- auth-page wrapper -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@10.15.5/dist/sweetalert2.min.css">
    <div class="auth-page-wrapper auth-bg-cover py-5 d-flex justify-content-center align-items-center min-vh-100">
        <div class="bg-overlay"></div>
        <!-- auth-page content -->
        <div class="auth-page-content overflow-hidden pt-lg-5">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card overflow-hidden m-0">
                            <div class="row justify-content-center g-0">
                                <div class="col-lg-6">
                                    <div class="p-lg-5 p-4 auth-one-bg h-100">
                                        <div class="bg-overlay"></div>
                                        <div class="position-relative h-100 d-flex flex-column">
                                            <div class="mb-4">
                                                <a href="<?= $global_var['config']['site_url'] ?>" class="d-block">
                                                    <img width="200px" height="150px" src="<?= $global_var['config']['site_url'] . $global_var['config']['logo'] ?>" alt="" height="18">
                                                </a>
                                            </div>
                                            <div class="mt-auto">
                                                <div class="mb-3">
                                                    <i class="ri-double-quotes-l display-4 text-success"></i>
                                                </div>

                                                <div id="qoutescarouselIndicators" class="carousel slide" data-bs-ride="carousel">

                                                    <div class="carousel-inner text-center text-white-50 pb-5">
                                                        <div class="carousel-item active">
                                                            <p class="fs-15 fst-italic">Welcome to Library Managment System</p>
                                                        </div>

                                                    </div>
                                                </div>
                                                <!-- end carousel -->

                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-lg-6">
                                    <div class="p-lg-5 p-4">
                                        <div>
                                            <h5 class="text-primary">Create your Student Account</h5>
                                            <p class="text-muted">Get your account now on <?= $global_var['config']['site_name'] ?></p>
                                        </div>

                                        <div class="mt-4">
                                            <form class="needs-validation" novalidate id="register">
                                                <div class="row">
                                                    <div class="mb-3 col-md-6">
                                                        <label for="username" class="form-label">Firstname <span class="text-danger">*</span></label>
                                                        <input type="text" class="form-control" name="firstname" placeholder="Enter Firstname" required>

                                                    </div>
                                                    <div class="mb-3 col-md-6">
                                                        <label for="username" class="form-label">Lastname <span class="text-danger">*</span></label>
                                                        <input type="text" class="form-control" name="lastname" placeholder="Enter Lastname" required>

                                                    </div>
                                                    <div class="mb-3 col-md-6">
                                                        <label for="username" class="form-label">Othername <span class="text-danger">*</span></label>
                                                        <input type="text" name="othername" class="form-control" id="username" placeholder="Enter othername" required>

                                                    </div>
                                                    <div class="mb-3 col-md-6">
                                                        <label for="username" class="form-label">Choose Class <span class="text-danger">*</span></label>

                                                        <select name="class_id" class="form-control">
                                                            <option value="">--Select Class --</option>
                                                            <?php foreach ($db->get("classes") as $class): ?>
                                                                <option value="<?= $class->id ?>"><?= $class->abbrev ?></option>
                                                            <?php endforeach; ?>

                                                        </select>
                                                    </div>
                                                    <div class="mb-3 col-md-6">
                                                        <label for="useremail" class="form-label">Tel No. <span class="text-danger">*</span></label>
                                                        <input type="text" class="form-control" name="tel" placeholder="Enter Tel." required>

                                                    </div>
                                                    <div class="mb-3 col-md-6">
                                                        <label for="useremail" class="form-label">Email <span class="text-danger">*</span></label>
                                                        <input type="email" class="form-control" name="email" placeholder="Enter email address" required>

                                                    </div>

                                                    <div class="mb-3 col-md-6">
                                                        <label class="form-label" for="password-input">Password</label>

                                                        <input type="password" name="password" class="form-control pe-5 password-input" onpaste="return false" placeholder="Enter password" id="password-input" aria-describedby="passwordInput" pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}" required>

                                                    </div>
                                                    <div class="mb-3 col-md-6">
                                                        <label class="form-label" for="password-input">Confirm Password</label>

                                                        <input type="password" name="confirm_password" class="form-control pe-5 password-input" onpaste="return false" placeholder="Enter password" id="password-input" aria-describedby="passwordInput" pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}" required>

                                                    </div>

                                                </div>

                                                <!-- <div class="mb-4">
                                                    <p class="mb-0 fs-12 text-muted fst-italic">By registering you agree to the Velzon <a href="#" class="text-primary text-decoration-underline fst-normal fw-medium">Terms of Use</a></p>
                                                </div> -->


                                                <div class="form-group">


                                                    <div class="mt-4">
                                                        <button class="btn button btn-success w-100 button" type="submit">Register</button>
                                                    </div>

                                                </div>
                                            </form>
                                        </div>

                                        <div class="mt-2 text-center">
                                            <p class="mb-0">Already have an account ? <a href="index.php?page=login" class="fw-semibold text-primary text-decoration-underline"> Login</a> </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- end card -->
                    </div>
                    <!-- end col -->

                </div>
                <!-- end row -->
            </div>
            <!-- end container -->
        </div>
        <!-- end auth page content -->
        <!-- SweetAlert2 JS -->
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

        <script>
            $('#register').on('submit', function(e) {
                e.preventDefault();
                $.ajax({
                    url: request() + '?file=auth&action=register',
                    method: 'POST',
                    contentType: false,
                    processData: false,
                    data: new FormData(this),
                    beforeSend: function() {
                        $('.button').html('Processing...');
                        $('.button').addClass('disabled');
                    },
                    success: function(response) {
                        console.log(response)
                        $('.button').html('Register');
                        $('.button').removeClass('disabled');
                        if (response.status == 200) {
                            Swal.fire({
                                title: "Good job!",
                                text: response.message,
                                icon: "success",
                                timer: 2000,
                                showConfirmButton: false
                            }).then(() => {
                                window.location.href = response.url;
                            });
                        } else {
                            Swal.fire({
                                title: "Oops!",
                                text: response.message,
                                icon: "error",
                                confirmButtonColor: "#6c757d"
                            });
                        }
                    }
                });
            });
        </script>