   <?php
    $req_details = $db->where("id", secure_data($_GET['id']))->getOne("borrow_requests");
    $book_details = $db->where("id", $req_details->book_id)->getOne("books");
    $student_details = $db->where('id', $req_details->student_id)->getOne('users');
    $borrowed_copy = $db->where('requesition_id', $req_details->id)->getOne('borrowed_copies');
    $over_due_days_limit = 2;
    $days = getBorrowedBookRemainingDays(date('y-m-d', strtotime($req_details->return_date)));

    ?>
   <div class="main-content">


       <div class="page-content">
           <div class="container-fluid">

               <!-- start page title -->
               <div class="row">
                   <div class="col-12">
                       <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                           <h4 class="mb-sm-0">Borrow Requestion Details</h4>

                           <div class="page-title-right">
                               <ol class="breadcrumb m-0">
                                   <li class="breadcrumb-item"><a href="javascript: void(0);">Home</a></li>
                                   <li class="breadcrumb-item active">All Books</li>
                               </ol>
                           </div>

                       </div>
                   </div>
               </div>
               <div class="row">
                   <div class="col-12">

                       <div class="col-xxl-4">
                           <div class="card border-info shadow-lg">
                               <div class="card-header bg-info text-white">
                                   <h6 class="card-title mb-0 d-flex justify-content-between align-items-center">
                                       Book Borrow Request Details

                                   </h6>
                               </div>
                               <div class="card-body">
                                   <p><strong>Student Name : </strong><?= $student_details->firstname . ' ' . $student_details->lastname . ' ' . $student_details->othername ?></p>
                                   <p><strong>Borrowed Book:</strong> <?= $book_details->title . '<b> by : </b>' . $db->where('id', $book_details->author_id)->getOne('book_authors')->names; ?> <br>
                                       <strong>ISBN:</strong> <?= $book_details->isbn; ?>
                                   </p>
                                   <p>
                                       <strong>Borrowing Reason : </strong><?= $req_details->reason; ?>
                                   </p>
                                   <p>
                                   <div class="d-flex justify-content-between align-items-center p-3 border rounded">
                                       <div>
                                           <h5 class="text-primary mb-0">📚 Requested Copies: <?= $req_details->no_of_copies; ?></h5>
                                           <?php if ($req_details->aprove_status == 1) { ?>

                                               <p class="fw-bold text-danger fs-4">Borrowed Book Copy No. : <?= (empty($borrowed_copy) ? '' : $db->where('id', $borrowed_copy->book_copy_id)->getOne('book_copies')->book_copy_no); ?></p>
                                           <?php } ?>

                                       </div>
                                       <?php if ((empty($req_details->aprove_status) || $req_details->aprove_status == 2) && $global_var['user']['user_type'] != 'stud') { ?>
                                           <div>
                                               <h5 class="text-success mb-0">✅ Available Copies:</h5>
                                               <p class="fw-bold text-success fs-4"><?= count($db->where('book_id', $book_details->id)->where('status', 'available')->get('book_copies')); ?></p>
                                           </div>
                                       <?php } ?>
                                   </div>
                                   </p>
                                   <p>
                                       <strong>Return Date:</strong> <?= date('d/m/Y', strtotime($req_details->return_date)); ?>
                                   </p>
                                   <hr>
                                   <?php if ($req_details->aprove_status == 1 && empty($borrowed_copy->return_status)) { ?>
                                       <p><strong>Approval Status:</strong>
                                           <span class="badge bg-success">Approved</span><br><br>
                                           <strong>Days remaining : </strong>
                                           <?php

                                            if ($days <  1) {
                                                echo '<span class="badge bg-danger">Overdue by ' . abs($days) . ' days</span>';
                                            } else {
                                                echo $days . ' Days';
                                            }

                                            ?>

                                       </p>


                                       <p>
                                       <?php } elseif ($req_details->aprove_status == 2) { ?>
                                           <strong>Approval Status: </strong><span class="badge bg-danger"> Rejected</span><br><br>
                                       <p><strong>Rejection Reason: </strong><?= $req_details->rejection_reason ?> </p>

                                   <?php } else { ?>
                                       <strong>Approval Status: </strong><span class="badge bg-info"> Pending</span>
                                   <?php } ?>
                                   <hr>

                                   <div class="d-flex mt-3">
                                       <?php if ($global_var['user']['user_type'] != 'stud') {
                                            if ($req_details->aprove_status != 1) { ?>
                                               <button data-bs-toggle="modal" data-bs-target="#approve_req" class="btn btn-success m-1"><i class="fas fa-check"></i> Approve</button>
                                               <?php if ($req_details->aprove_status != 2) { ?>
                                                   <button data-bs-toggle="modal" data-bs-target="#reject_req" class="btn btn-danger m-1"><i class="fas fa-times"></i> Reject</button>
                                               <?php }
                                            } else { ?>
                                               <button data-bs-toggle="modal" data-bs-target="#confirm_return" class="btn btn-success m-1"><i class="fas fa-check"></i> Confirm Return</button>
                                               <?php if ($days < 0 && abs($days) > $over_due_days_limit) { ?>
                                                   <button data-bs-toggle="modal" data-bs-target="#mark_as_lost" class="btn btn-danger m-1"><i class="fas fa-cancel"></i> Mark As Lost</button>

                                               <?php }
                                            }
                                        } else {
                                            if ($req_details->aprove_status != 1) {
                                                if ($req_details->aprove_status != 2) { ?>
                                                   <a href="index.php?page=edit_requistion&id=<?= $req_details->id ?>" class="btn btn-warning m-1"><i class="fas fa-edit"></i> Edit</a>
                                               <?php } ?>
                                               <button class="btn btn-secondary m-1 delete"><i class="fas fa-trash"></i> Delete</button>
                                       <?php  }
                                        } ?>
                                   </div>
                               </div>
                           </div>
                       </div><!-- end col -->
                   </div><!-- end row -->
               </div><!-- end col -->
           </div><!-- end row -->
       </div><!-- end col -->
   </div><!-- end row -->
   <!-- Add new Borrow request Modal -->
   <div id="confirm_return" class="modal fade fadeInUp" tabindex="-1" aria-labelledby="fadeInUpModalLabel" aria-hidden="true" style="display: none;">
       <div class="modal-dialog modal-dialog-centered">
           <div class="modal-content">
               <div class="modal-header">
                   <h5 class="modal-title" id="fadeInUpModalLabel">Confirm Book Return</h5>
                   <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
               </div>
               <div class="modal-body">
                   <form id="confirm_borrow_return">
                       <input type="text" name="book_id" value="<?= $req_details->book_id ?>" hidden />
                       <input type="text" name="book_copy_id" value="<?= $borrowed_copy->book_copy_id ?>" hidden />
                       <input type="text" name="id" value="<?= $req_details->id ?>" hidden />
                       <input type="text" name="student_id" value="<?= $req_details->student_id ?>" hidden />
                       <div class="row gy-4">


                           <!--end col-->


                           <div class="col-xxl-3 col-md-6 d-none">
                               <div>
                                   <label for="placeholderInput" class="form-label">No. Of Copies Returned</label>
                                   <input type="text" class="form-control" name="no_of_copies" placeholder="No. Of Copies returned">
                               </div>
                           </div>
                           <div class="col-xxl-3 col-md-12">
                               <div>
                                   <label for="placeholderInput" class="form-label">Return date</label>
                                   <input type="date" class="form-control" name="return_date">
                               </div>
                           </div>
                           <div class="col-xxl-3 col-md-12">
                               <div class="form-check">
                                   <input type="checkbox" value="1" class="form-check-input" name="damaged">
                                   <label for="damagedCheckbox" class="form-check-label">Mark As Damaged</label>
                               </div>
                           </div>

                           <div class="col-xxl-3 col-md-12">
                               <div>
                                   <label for="placeholderInput" class="form-label">Comment</label>
                                   <textarea placeholder="Enter Comment here.." class="form-control" name="comment"></textarea>

                               </div>
                           </div>
                           <!--end col-->


                       </div>
                       <hr>
                       <div class="modal-footer mt-4">
                           <button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
                           <button type="submit" class="btn btn-primary">Confirm</button>
                       </div>
               </div>
               </form>

           </div><!-- /.modal-content -->
       </div><!-- /.modal-dialog -->
   </div><!-- /.modal -->
   <div id="mark_as_lost" class="modal fade fadeInUp" tabindex="-1" aria-labelledby="fadeInUpModalLabel" aria-hidden="true" style="display: none;">
       <div class="modal-dialog modal-dialog-centered">
           <div class="modal-content">
               <div class="modal-header">
                   <h5 class="modal-title" id="fadeInUpModalLabel">Mark borrowed book as lost</h5>
                   <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
               </div>
               <div class="modal-body">
                   <form id="confirm_lost_borrowed_book">
                       <input type="text" name="book_copy_id" value="<?= $borrowed_copy->book_copy_id ?>" hidden />

                       <input type="text" name="id" value="<?= $req_details->id ?>" hidden />
                       <input type="text" name="student_id" value="<?= $req_details->student_id ?>" hidden />
                       <div class="row gy-4">


                           <div class="col-xxl-3 col-md-12">
                               <div>
                                   <label for="placeholderInput" class="form-label">Comment</label>
                                   <textarea placeholder="Enter Comment here.." class="form-control" name="comment"></textarea>

                               </div>
                           </div>
                           <!--end col-->


                       </div>
                       <hr>
                       <div class="modal-footer mt-4">
                           <button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
                           <button type="submit" class="btn btn-primary">Confirm</button>
                       </div>
               </div>
               </form>

           </div><!-- /.modal-content -->
       </div><!-- /.modal-dialog -->
   </div><!-- /.modal -->
   <div id="reject_req" class="modal fade fadeInUp" tabindex="-1" aria-labelledby="fadeInUpModalLabel" aria-hidden="true" style="display: none;">
       <div class="modal-dialog modal-dialog-centered">
           <div class="modal-content">
               <div class="modal-header">
                   <h5 class="modal-title" id="fadeInUpModalLabel">Reject Borrow Request</h5>
                   <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
               </div>
               <div class="modal-body">
                   <form id="reject_borrow">

                       <input type="text" name="id" value="<?= $req_details->id ?>" hidden />
                       <div class="row gy-4">



                           <div class="col-xxl-3 col-md-12">
                               <div>
                                   <label for="placeholderInput" class="form-label">Reason For Rejecting</label>
                                   <textarea placeholder="Enter Reason here.." class="form-control" name="rejection_reason"></textarea>

                               </div>
                           </div>
                           <!--end col-->


                       </div>
                       <hr>
                       <div class="modal-footer mt-4">
                           <button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
                           <button type="submit" class="btn btn-primary">Reject Request</button>
                       </div>
               </div>
               </form>

           </div><!-- /.modal-content -->
       </div><!-- /.modal-dialog -->
   </div><!-- /.modal -->
   <div id="approve_req" class="modal fade fadeInUp" tabindex="-1" aria-labelledby="fadeInUpModalLabel" aria-hidden="true" style="display: none;">
       <div class="modal-dialog modal-dialog-centered">
           <div class="modal-content">
               <div class="modal-header">
                   <h5 class="modal-title" id="fadeInUpModalLabel">Approve Borrow Request</h5>
                   <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
               </div>
               <div class="modal-body">
                   <form id="apporove_requestion">

                       <input type="text" name="id" value="<?= $req_details->id ?>" hidden />
                       <input type="text" name="student_id" value="<?= $req_details->student_id ?>" hidden />
                       <input type="text" name="book_id" value="<?= $req_details->book_id ?>" hidden />

                       <div class="row gy-4">

                           <div class="col-xxl-3 col-md-12">
                               <div>
                                   <label for=" basiInput" class="form-label">Select Book Copy to Assign Student</label>
                                   <select id="authorSelect" name="book_copy_id" class="form-control selectpicker" data-live-search="true">

                                       <option value=" ">--Select Book Copy--</option>
                                       <?php foreach ($db->where("book_id", $book_details->id)->where("status", "available")->get("book_copies") as $value) { ?>
                                           <option value="<?= $value->id ?>"><?= $value->book_copy_no ?></option>
                                       <?php } ?>
                                   </select>
                               </div>
                           </div>


                           <div class="col-xxl-3 col-md-12">
                               <div>
                                   <label for="placeholderInput" class="form-label">Attach Any Comment</label>
                                   <textarea placeholder="Enter Comment here.." class="form-control" name="assign_comment"></textarea>

                               </div>
                           </div>
                           <!--end col-->


                       </div>
                       <hr>
                       <div class="modal-footer mt-4">
                           <button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
                           <button type="submit" class="btn btn-primary">Approve Request</button>
                       </div>
               </div>
               </form>

           </div><!-- /.modal-content -->
       </div><!-- /.modal-dialog -->
   </div><!-- /.modal -->
   <script>
       $('#confirm_borrow_return').on('submit', function(e) {

           e.preventDefault();
           $.ajax({
               url: request() + '?file=borrow&action=confirm_return',
               method: 'POST',
               data: new FormData(this),
               contentType: false,
               processData: false,
               cache: false,
               success: function(response) {
                   console.log(response);
                   if (response.status == 200) {
                       Swal.fire({
                           title: "Good job!",
                           text: response.message,
                           icon: "success",
                           showConfirmButton: true,
                       });
                       setTimeout(function() {
                           window.location.href = response.url;
                       }, 2e3);

                   } else {
                       Swal.fire({
                           title: "Oops!",
                           text: response.message,
                           icon: "error",
                           cancelButtonClass: "btn btn-danger ml-2 mt-2",
                           confirmButtonColor: "#6c757d"
                       });
                   }
               }
           });
       });
       $('#confirm_lost_borrowed_book').on('submit', function(e) {

           e.preventDefault();
           $.ajax({
               url: request() + '?file=borrow&action=mark_as_lost',
               method: 'POST',
               data: new FormData(this),
               contentType: false,
               processData: false,
               cache: false,
               success: function(response) {
                   console.log(response);
                   if (response.status == 200) {
                       Swal.fire({
                           title: "Good job!",
                           text: response.message,
                           icon: "success",
                           showConfirmButton: true,
                       });
                       setTimeout(function() {
                           window.location.href = response.url;
                       }, 2e3);

                   } else {
                       Swal.fire({
                           title: "Oops!",
                           text: response.message,
                           icon: "error",
                           cancelButtonClass: "btn btn-danger ml-2 mt-2",
                           confirmButtonColor: "#6c757d"
                       });
                   }
               }
           });
       });


       $(document).ready(function() {
           // Approve Button Click
           $(document).on("click", ".delete", function() {
               var el = this;
               var req_id = '<?= secure_data($_GET['id']) ?>';

               Swal.fire({
                   title: 'Are you sure?',
                   text: "You want to delete this borrow Request?",
                   icon: 'warning',
                   showCancelButton: true,
                   confirmButtonColor: '#3085d6',
                   cancelButtonColor: '#d33',
                   confirmButtonText: 'Yes, approve it!'
               }).then((result) => {
                   if (result.isConfirmed) {
                       // AJAX Request
                       $.ajax({
                           url: request() + '?file=borrow&action=delete_borrow_request',
                           type: 'POST',
                           data: {
                               id: req_id,

                           },
                           success: function(response) {
                               console.log(response);
                               if (response.status == 200) {
                                   Swal.fire({
                                       title: "Good job!",
                                       text: response.message,
                                       icon: "success",
                                       showConfirmButton: false,
                                   });
                                   setTimeout(function() {
                                       window.location.href = response.url;
                                   }, 2e3);
                               } else {
                                   Swal.fire({
                                       title: "Oops!",
                                       text: response.message,
                                       icon: "error",
                                       cancelButtonClass: "btn btn-danger ml-2 mt-2",
                                       confirmButtonColor: "#6c757d"
                                   });
                               }
                           }
                       });
                   }
               });
           })
       })


       $('#reject_borrow').on('submit', function(e) {
           e.preventDefault();
           Swal.fire({
               title: 'Are you sure?',
               text: "You want to Reject this borrow Request?",
               icon: 'warning',
               showCancelButton: true,
               confirmButtonColor: '#3085d6',
               cancelButtonColor: '#d33',
               confirmButtonText: 'Yes, Reject it!'
           }).then((result) => {
               if (result.isConfirmed) {
                   // AJAX Request
                   $.ajax({
                       url: request() + '?file=borrow&action=reject_borrow_request',
                       type: 'POST',
                       data: new FormData(this),
                       contentType: false,
                       processData: false,
                       cache: false,
                       success: function(response) {
                           console.log(response);
                           if (response.status == 200) {
                               Swal.fire({
                                   title: "Good job!",
                                   text: response.message,
                                   icon: "success",
                                   showConfirmButton: false,
                               });
                               setTimeout(function() {
                                   window.location.href = response.url;
                               }, 2e3);
                           } else {
                               Swal.fire({
                                   title: "Oops!",
                                   text: response.message,
                                   icon: "error",
                                   cancelButtonClass: "btn btn-danger ml-2 mt-2",
                                   confirmButtonColor: "#6c757d"
                               });
                           }
                       }
                   });
               }
           });
       });
       $('#apporove_requestion').on('submit', function(e) {
           e.preventDefault();
           Swal.fire({
               title: 'Are you sure?',
               text: "You want to Approve this borrow Request?",
               icon: 'warning',
               showCancelButton: true,
               confirmButtonColor: '#3085d6',
               cancelButtonColor: '#d33',
               confirmButtonText: 'Yes, Approve it!'
           }).then((result) => {
               if (result.isConfirmed) {
                   // AJAX Request
                   $.ajax({
                       url: request() + '?file=borrow&action=approve_borrow_request',
                       type: 'POST',
                       data: new FormData(this),
                       contentType: false,
                       processData: false,
                       cache: false,
                       success: function(response) {
                           console.log(response);
                           if (response.status == 200) {
                               Swal.fire({
                                   title: "Good job!",
                                   text: response.message,
                                   icon: "success",
                                   showConfirmButton: false,
                               });
                               setTimeout(function() {
                                   window.location.href = response.url;
                               }, 2e3);
                           } else {
                               Swal.fire({
                                   title: "Oops!",
                                   text: response.message,
                                   icon: "error",
                                   cancelButtonClass: "btn btn-danger ml-2 mt-2",
                                   confirmButtonColor: "#6c757d"
                               });
                           }
                       }
                   });
               }
           });
       });
   </script>