<?php
$all_requests = $db->orderBy('id', 'DESC')->get('borrow_requests');
if ($the_ken['user']['user_type'] == 'stud') {
    $all_requests = $db->orderBy('id', 'DESC')->where('student_id', $the_ken['user']['id'])->get('borrow_requests');
}
?>
<div class="main-content">


    <div class="page-content">
        <div class="container-fluid">

            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                        <h4 class="mb-sm-0">All Borrow Reguisitions</h4>

                        <div class="page-title-right">
                            <ol class="breadcrumb m-0">
                                <li class="breadcrumb-item"><a href="javascript: void(0);">Home</a></li>
                                <li class="breadcrumb-item active">Book Requisitions</li>
                            </ol>
                        </div>

                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">

                        <div class="card-body">
                            <div class="listjs-table" id="customerList">
                                <div class="row g-4 mb-3">
                                    <div class="col-sm-auto">
                                        <?php if ($the_ken['user']['user_type'] == 'stud') { ?>
                                            <div>
                                                <a data-bs-toggle="modal" data-bs-target="#new_borrow_request" type="button" class="btn btn-success add-btn"><i class="ri-add-line align-bottom me-1"></i> Add New Borrow Request</a>

                                            </div>
                                        <?php } ?>
                                    </div>
                                    <div class="col-sm-auto">
                                        <div>


                                        </div>
                                    </div>
                                    <div class="col-sm">
                                        <div class="d-flex justify-content-sm-end">
                                            <div class="search-box ms-2">
                                                <a href="" type="button" class="btn btn-success add-btn"><i class="ri-add-line align-bottom me-1"></i> Filter Requests</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <?php if ($the_ken['user']['user_type'] != 'stud') { ?>
                                    <div class="table-responsive mt-3 mb-1">
                                        <table id="myTable" class="table table-bordered table-striped">
                                            <thead class="table-light">
                                                <tr>
                                                    <th scope="col">
                                                        S/No.
                                                    </th>
                                                    <th class="sort" data-sort="title">Student Name</th>
                                                    <th class="sort" data-sort="description">Class/Course</th>
                                                    <th class="sort" data-sort="date">Requested Book</th>
                                                    <th class="sort" data-sort="date">No._Of_Copes</th>
                                                    <th class="sort" data-sort="date">Status</th>
                                                    <th class="sort" data-sort="date">Return Date</th>
                                                    <th class="sort" data-sort="action">Action</th>
                                                </tr>
                                            </thead>
                                            <tbody class="list form-check-all">

                                                <?php
                                                $sn = 0;
                                                foreach ($all_requests as $value):
                                                    $book_details = $db->where("id", $value->book_id)->getOne("books");
                                                    $student_details = $db->where('id', $value->student_id)->getOne('users');

                                                    $sn++;
                                                ?>
                                                    <tr>
                                                        <th scope="row">
                                                            <?= $sn ?>
                                                        </th>
                                                        <td><?= $student_details->firstname . ' ' . $student_details->lastname ?></td>
                                                        <td><?= $db->where('id', $student_details->class_id)->getOne('classes')->abbrev ?></td>
                                                        <td><?= $book_details->title . '  - ' . $book_details->author ?></td>
                                                        <td><?= $value->no_of_copies ?></td>
                                                        <td><?php if ($value->aprove_status == 1) {
                                                                echo '<span class="badge bg-success">Approved</span></td>';
                                                            } else {
                                                                echo '<span class="badge bg-info">Pending</span></td>';
                                                            } ?>
                                                        <td class="date"><?= date('d/m/Y', strtotime($value->return_date)) ?></td>

                                                        <td>
                                                            <a href="index.php?page=req_details&id=<?= $value->id ?>" class="btn btn-sm btn-success " href="">View Details</a>
                                                        </td>
                                                    </tr>
                                                <?php endforeach; ?>
                                            </tbody>
                                        </table>

                                    </div>
                                <?php } else { ?>

                                    <div class="table-responsive mt-3 mb-1">
                                        <table id="myTable" class="table table-bordered table-striped">
                                            <thead class="table-light">
                                                <tr>
                                                    <th scope="col">
                                                        S/No.
                                                    </th>
                                                    <th class="sort" data-sort="date">Requested Book</th>
                                                    <th class="sort" data-sort="date">No._Of_Copes</th>
                                                    <th class="sort" data-sort="date">Status</th>
                                                    <th class="sort" data-sort="date">Return Date</th>
                                                    <th class="sort" data-sort="action">Action</th>
                                                </tr>
                                            </thead>
                                            <tbody class="list form-check-all">

                                                <?php
                                                $sn = 0;
                                                foreach ($all_requests as $value):
                                                    $book_details = $db->where("id", $value->book_id)->getOne("books");

                                                    $sn++;
                                                ?>
                                                    <tr>
                                                        <th scope="row">
                                                            <?= $sn ?>
                                                        </th>

                                                        <td><?= $book_details->title . '  - ' . $book_details->author ?></td>
                                                        <td><?= $value->no_of_copies ?></td>
                                                        <td><?php if ($value->aprove_status == 1) {
                                                                echo '<span class="badge bg-success">Approved</span></td>';
                                                            } else {
                                                                echo '<span class="badge bg-info">Pending</span></td>';
                                                            } ?>
                                                        <td class="date"><?= date('d/m/Y', strtotime($value->return_date)) ?></td>

                                                        <td>
                                                            <a href="index.php?page=req_details&id=<?= $value->id ?>" class="btn btn-sm btn-success " href="">View Details</a>
                                                        </td>
                                                    </tr>
                                                <?php endforeach; ?>
                                            </tbody>
                                        </table>

                                    </div>

                                <?php } ?>


                            </div>
                        </div><!-- end card -->
                    </div>
                    <!-- end col -->
                </div>
                <!-- end col -->
            </div>
            <!-- end row -->



        </div>
    </div>

    <script type="text/javascript">

    </script>