<?php
$all_requests = $db->orderBy('id', 'DESC')->where('return_status', 1)->get('borrow_requests');
if ($global_var['user']['user_type'] == 'stud') {
    $all_requests = $db->orderBy('id', 'DESC')->where('student_id', $global_var['user']['id'])->where('return_status IS NOT NULL')->get('borrow_requests');
}
?>
<div class="main-content">


    <div class="page-content">
        <div class="container-fluid">

            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                        <h4 class="mb-sm-0">All Borrow Books</h4>

                        <div class="page-title-right">
                            <ol class="breadcrumb m-0">
                                <li class="breadcrumb-item"><a href="javascript: void(0);">Home</a></li>
                                <li class="breadcrumb-item active">Borrowed Books</li>
                            </ol>
                        </div>

                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">

                        <div class="card-body">
                            <div class="listjs-table" id="customerList">
                                <div class="row g-4 mb-3">

                                    <div class="col-sm d-none">
                                        <div class="d-flex justify-content-sm-end">
                                            <div class="search-box ms-2">
                                                <a href="" type="button" class="btn btn-success add-btn"><i class="ri-add-line align-bottom me-1"></i> Filter </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="table-responsive mt-3 mb-1">
                                    <?php if ($global_var['user']['user_type'] != 'stud') { ?>
                                        <table id="myTable" class="table table-bordered table-striped">
                                            <thead class="table-light">
                                                <tr>
                                                    <th scope="col">
                                                        S/No.
                                                    </th>
                                                    <th class="sort" data-sort="title">Student Name</th>
                                                    <th class="sort" data-sort="description">Class</th>
                                                    <th class="sort" data-sort="date">Borrowed Book</th>
                                                    <th class="sort" data-sort="date">Copies</th>
                                                    <th class="sort" data-sort="date">Return Status</th>
                                                    <th class="sort" data-sort="date">Returned On</th>

                                                    <th class="sort" data-sort="action">Action</th>
                                                </tr>
                                            </thead>
                                            <tbody class="list form-check-all">

                                                <?php
                                                $sn = 0;
                                                foreach ($all_requests as $value):
                                                    $book_details = $db->where("id", $value->book_id)->getOne("books");
                                                    $student_details = $db->where('id', $value->student_id)->getOne('users');

                                                    $sn++;
                                                ?>
                                                    <tr>
                                                        <th scope="row">
                                                            <?= $sn ?>
                                                        </th>
                                                        <td><?= $student_details->firstname . ' ' . $student_details->lastname ?></td>
                                                        <td><?= $db->where('id', $student_details->class_id)->getOne('classes')->abbrev ?></td>
                                                        <td><?= $book_details->title . ' ' . $book_details->author ?></td>
                                                        <td><?= $value->no_of_copies ?></td>
                                                        <td><?php if ($value->return_status == 1) {
                                                                echo '<span class="badge bg-success">Returned</span></td>';
                                                            } else {
                                                                echo '<span class="badge bg-info">Pending</span></td>';
                                                            } ?></td>
                                                        <td class="date"><?= date('d/m/Y', strtotime($value->returned_on)) ?></td>

                                                        <td>
                                                            <a title='View Details' href="index.php?page=borrow_history&id=<?= $value->id ?>" class="btn btn-sm btn-success " href=""><i class="fas fa-eye"></i> </a>
                                                        </td>
                                                    </tr>
                                                <?php endforeach; ?>
                                            </tbody>
                                        </table>
                                    <?php } else { ?>
                                        <table id="myTable" class="table table-bordered table-striped">
                                            <thead class="table-light">
                                                <tr>
                                                    <th scope="col">
                                                        S/No.
                                                    </th>


                                                    <th class="sort" data-sort="date">Borrowed Book</th>
                                                    <th class="sort" data-sort="date">Copies</th>
                                                    <th class="sort" data-sort="date">Borrow Date</th>
                                                    <th class="sort" data-sort="date">Due Date</th>
                                                    <th class="sort" data-sort="date">Return Date</th>
                                                    <th class="sort" data-sort="date">Overdue Status</th>
                                                    <th class="sort" data-sort="action">Action</th>
                                                </tr>
                                            </thead>
                                            <tbody class="list form-check-all">

                                                <?php
                                                $sn = 0;
                                                foreach ($all_requests as $value):
                                                    $book_details = $db->where("id", $value->book_id)->getOne("books");
                                                    $student_details = $db->where('id', $value->student_id)->getOne('users');

                                                    $sn++;
                                                ?>
                                                    <tr>
                                                        <th scope="row">
                                                            <?= $sn ?>
                                                        </th>


                                                        <td><?= $book_details->title  ?></td>

                                                        <td><?= $value->no_of_copies ?></td>
                                                        <td><?= date('d/m/Y', strtotime($value->date_approved)) ?></td>
                                                        <td class="date"><?= date('d/m/Y', strtotime($value->return_date)) ?></td>
                                                        <td><?= date('d/m/Y', strtotime($value->returned_on)) ?></td>

                                                        <?php if ($value->returned_on > $value->return_date) {
                                                            echo ' <td><span class="badge bg-info">Yes</span></td>';
                                                        } else {
                                                            echo ' <td><span class="badge bg-info">Not</span></td>';
                                                        } ?>


                                                        <td>
                                                            <a title='View Details' href="index.php?page=borrow_history&id=<?= $value->id ?>" class="btn btn-sm btn-success " href=""><i class="fas fa-eye"></i> </a>
                                                        </td>
                                                    </tr>
                                                <?php endforeach; ?>
                                            </tbody>
                                        </table>
                                    <?php } ?>

                                </div>

                            </div>
                        </div><!-- end card -->
                    </div>
                    <!-- end col -->
                </div>
                <!-- end col -->
            </div>
            <!-- end row -->



        </div>
    </div>