<?php
$first_day_of_month = date('Y-m-01');
$page_title = "Borrow History from " . date('d/m/Y', strtotime($first_day_of_month)) . " to today";

$all_borrowed_copies = $db->orderBy('id', 'DESC')->where('date_created', $first_day_of_month, '>')->where('return_status IS NOT NULL')->get('borrowed_copies');
if ($global_var['user']['user_type'] == 'stud') {
    $all_borrowed_copies = $db->orderBy('id', 'DESC')->where('date_created', $first_day_of_month, '>')->where('student_id', $global_var['user']['id'])->where('return_status IS NOT NULL')->get('borrowed_copies');
}
if (isset($_GET['start_date']) && isset($_GET['end_date'])) {
    $all_borrowed_copies = $db->where('date_created', secure_data($_GET['start_date']), '>=')
        ->where('date_created', secure_data($_GET['end_date']), '<=')
        ->orderBy('id', 'DESC')
        ->where('return_status IS NOT NULL')
        ->get('borrowed_copies');
    if ($global_var['user']['user_type'] == 'stud') {
        $all_borrowed_copies = $db->where('student_id', $global_var['user']['id'])->where('date_created', secure_data($_GET['start_date']), '>=')
            ->where('date_created', secure_data($_GET['end_date']), '<=')
            ->orderBy('id', 'DESC')
            ->where('return_status IS NOT NULL')
            ->get('borrowed_copies');
    }
    $page_title = 'Borrow History FROM ' . date('d/m/Y', strtotime($_GET['start_date'])) . ' TO ' . date('d/m/Y', strtotime($_GET['end_date']));
}

?>
<div class="main-content">


    <div class="page-content">
        <div class="container-fluid">

            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                        <h4 class="mb-sm-0"><?= $page_title; ?></h4>

                        <div class="page-title-right">
                            <ol class="breadcrumb m-0">
                                <li class="breadcrumb-item"><a href="javascript: void(0);">Home</a></li>
                                <li class="breadcrumb-item active">Borrowed Books</li>
                            </ol>
                        </div>

                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">

                        <div class="card-body">
                            <div class="listjs-table" id="customerList">
                                <div class="row g-4 mb-3">

                                    <div class="col-sm">
                                        <div class="d-flex justify-content-sm-end">
                                            <div class="search-box ms-2">
                                                <a data-bs-toggle="modal" data-bs-target="#filter_by_date" type="button" class="btn btn-primary add-btn"><i class="ri-filter-line align-bottom me-1"></i> Filter Requests By Date</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>


                                <div class="table-responsive mt-3 mb-1">
                                    <?php if ($global_var['user']['user_type'] != 'stud') { ?>
                                        <table id="myTable" class="table table-bordered table-striped">
                                            <thead class="table-light">
                                                <tr>
                                                    <th scope="col">
                                                        S/No.
                                                    </th>
                                                    <th class="sort" data-sort="title">Student Name</th>
                                                    <th class="sort" data-sort="description">Class</th>
                                                    <th class="sort" data-sort="date">Borrowed Book</th>
                                                    <th class="sort" data-sort="date">Copy No.</th>
                                                    <th class="sort" data-sort="date">Return Status</th>
                                                    <th class="sort" data-sort="date">Returned On</th>

                                                    <th class="sort" data-sort="action">Action</th>
                                                </tr>
                                            </thead>
                                            <tbody class="list form-check-all">

                                                <?php
                                                $sn = 0;
                                                foreach ($all_borrowed_copies as $value):
                                                    $request_details = $db->where('id', $value->requesition_id)->getOne('borrow_requests');
                                                    $book_details = $db->where("id", $request_details->book_id)->getOne("books");
                                                    $student_details = $db->where('id', $value->student_id)->getOne('users');

                                                    $sn++;
                                                ?>
                                                    <tr>
                                                        <th scope="row">
                                                            <?= $sn ?>
                                                        </th>
                                                        <td><?= $student_details->firstname . ' ' . $student_details->lastname ?></td>
                                                        <td><?= $db->where('id', $student_details->class_id)->getOne('classes')->abbrev ?></td>
                                                        <td><?= $book_details->title . ' ' . $db->where('id', $book_details->author_id)->getOne('book_authors')->names ?></td>
                                                        <td><?= $db->where('id', $value->book_copy_id)->getOne('book_copies')->book_copy_no  ?></td>
                                                        <?php if ($value->return_status == 'returned') {
                                                            echo '<td><span class="badge bg-success">Returned</span></td>
                                                             <td class="date">' . date("d/m/Y", strtotime($value->returned_on)) . '</td>';
                                                        } elseif ($value->return_status == 'damaged') {
                                                            echo '<td><span class="badge bg-danger">Damaged</span></td>
                                                             <td class="date">' . date("d/m/Y", strtotime($value->returned_on)) . '</td>';
                                                        } else if ($value->return_status == 'lost') {
                                                            echo '<td><span class="badge bg-danger">lost</span></td><td>___</td>';
                                                        } else {
                                                            echo '<td><span class="badge bg-info">Pending</span></td><td>___</td>';
                                                        } ?></td>


                                                        <td>
                                                            <a title='View Details' href="index.php?page=borrow_history&id=<?= $value->id ?>" class="btn btn-sm btn-success " href=""><i class="fas fa-eye"></i> </a>
                                                        </td>
                                                    </tr>
                                                <?php endforeach; ?>
                                            </tbody>
                                        </table>
                                    <?php } else { ?>
                                        <table id="myTable" class="table table-bordered table-striped">
                                            <thead class="table-light">
                                                <tr>
                                                    <th scope="col">
                                                        S/No.
                                                    </th>


                                                    <th class="sort" data-sort="date">Borrowed Book</th>
                                                    <th class="sort" data-sort="date">Copy No.</th>
                                                    <th class="sort" data-sort="date">Borrow Date</th>
                                                    <th class="sort" data-sort="date">Due Date</th>
                                                    <th class="sort" data-sort="date">Return Date</th>
                                                    <th class="sort" data-sort="date">Overdue Status</th>
                                                    <th class="sort" data-sort="action">Action</th>
                                                </tr>
                                            </thead>
                                            <tbody class="list form-check-all">

                                                <?php
                                                $sn = 0;
                                                foreach ($all_borrowed_copies as $value):
                                                    $request_details = $db->where('id', $value->requesition_id)->getOne('borrow_requests');
                                                    $book_details = $db->where("id", $request_details->book_id)->getOne("books");
                                                    $student_details = $db->where('id', $value->student_id)->getOne('users');;

                                                    $sn++;
                                                ?>
                                                    <tr>
                                                        <th scope="row">
                                                            <?= $sn ?>
                                                        </th>


                                                        <td><?= $book_details->title . '<b> by </b> ' . $db->where('id', $book_details->author_id)->getOne('book_authors')->names  ?></td>

                                                        <td><?= $db->where('id', $value->book_copy_id)->getOne('book_copies')->book_copy_no ?></td>
                                                        <td><?= date('d/m/Y', strtotime($value->date_created)) ?></td>
                                                        <td class="date"><?= date('d/m/Y', strtotime($request_details->return_date)) ?></td>

                                                        <?php if ($value->return_status == 'returned') {
                                                            echo '<td class="date">' . date("d/m/Y", strtotime($value->returned_on)) . '</td>';
                                                        } else if ($value->return_status == 'lost') {
                                                            echo '<td><span class="badge bg-danger">lost</span></td>';
                                                        } else if ($value->return_status == 'damaged') {
                                                            echo '<td class="date">' . date("d/m/Y", strtotime($value->returned_on)) . '</td>';
                                                        } else {
                                                            echo '<td><span class="badge bg-info">Pending</span></td><td>___</td>';
                                                        } ?></td>
                                                        <?php if ($value->return_status == 'lost') {
                                                            echo ' <td><span class="badge bg-danger">Yes</span></td>';
                                                        } else {
                                                            if ($value->returned_on > $request_details->return_date) {

                                                                echo ' <td><span class="badge bg-danger">Yes</span></td>';
                                                            } else {
                                                                echo ' <td><span class="badge bg-info">Not</span></td>';
                                                            }
                                                        }

                                                        ?>




                                                        <td>
                                                            <a title='View Details' href="index.php?page=borrow_history&id=<?= $value->id ?>" class="btn btn-sm btn-success " href=""><i class="fas fa-eye"></i> </a>
                                                        </td>
                                                    </tr>
                                                <?php endforeach; ?>
                                            </tbody>
                                        </table>
                                    <?php } ?>

                                </div>

                            </div>
                        </div><!-- end card -->
                    </div>
                    <!-- end col -->
                </div>
                <!-- end col -->
            </div>
            <!-- end row -->



        </div>
    </div>