<?php
$user_id = (empty($_GET['id']) ? $global_var['user']['id'] : __secure($_GET['id']));
$user_details = $db->where("id", $user_id)->getOne("users");
$user_type = "Student";
if ($user_details->user_type == 'lib') {
    $user_type = "Librarian";
}
$user_image = (empty($user_details->photo)) ? "/layout/assets/images/users/avatar-10.jpg" : $global_var['user']['photo'];

?>
<!-- ============================================================== -->
<!-- Start right Content here -->
<!-- ============================================================== -->
<div class="main-content">

    <div class="page-content">
        <div class="container-fluid">
            <div class="profile-foreground position-relative mx-n4 mt-n4">
                <div class="profile-wid-bg">
                    <img src="assets/images/profile-bg.jpg" alt="" class="profile-wid-img" />
                </div>
            </div>
            <div class="pt-4 mb-4 mb-lg-3 pb-lg-4 profile-wrapper">
                <div class="row g-4">
                    <div class="col-auto">
                        <div class="avatar-lg">

                            <img src="<?= $global_var['config']['site_url'] . $user_image ?>" alt="user-img" class="img-thumbnail rounded-circle" />
                        </div>
                    </div>
                    <!--end col-->
                    <div class="col">
                        <!-- address here  -->
                    </div>
                    <!--end col-->


                </div>
                <!--end row-->
            </div>

            <div class="row">
                <div class="col-lg-12">
                    <div>
                        <div class="d-flex profile-wrapper">
                            <!-- Nav tabs -->
                            <ul class="nav nav-pills animation-nav profile-nav gap-2 gap-lg-3 flex-grow-1" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link fs-14 active" data-bs-toggle="tab" href="#overview-tab" role="tab">
                                        <i class="ri-airplay-fill d-inline-block d-md-none"></i> <span class="d-none d-md-inline-block">Profile</span>
                                    </a>
                                </li>
                                <?php if (isset($_GET['id'])) { ?>
                                    <li class="nav-item">
                                        <a class="nav-link fs-14" data-bs-toggle="tab" href="#activities" role="tab">
                                            <i class="ri-list-unordered d-inline-block d-md-none"></i> <span class="d-none d-md-inline-block">Current Borrowed Books</span>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link fs-14" data-bs-toggle="tab" href="#projects" role="tab">
                                            <i class="ri-price-tag-line d-inline-block d-md-none"></i> <span class="d-none d-md-inline-block">Borrow History</span>
                                        </a>
                                    </li>
                                <?php } ?>
                            </ul>
                            <?php if (!isset($_GET['id'])) { ?>
                                <div class="flex-shrink-0">
                                    <a href="index.php?page=profile_setup" class="btn btn-success"><i class="ri-edit-box-line align-bottom"></i> Edit Profile</a>
                                </div>
                            <?php } ?>
                        </div>
                        <!-- Tab panes -->
                        <div class="tab-content pt-4 text-muted">
                            <div class="tab-pane active" id="overview-tab" role="tabpanel">
                                <div class="row">
                                    <div class="col-xxl-3">


                                        <div class="card">
                                            <div class="card-body">
                                                <h5 class="card-title mb-3">Profile Info</h5>
                                                <div class="table-responsive">
                                                    <table class="table table-borderless mb-0">
                                                        <tbody>
                                                            <tr>
                                                                <th class="ps-0" scope="row">First Name :</th>
                                                                <td class="text-muted"><?= $user_details->firstname ?></td>
                                                            </tr>
                                                            <tr>
                                                                <th class="ps-0" scope="row">Last Name :</th>
                                                                <td class="text-muted"><?= $user_details->lastname ?></td>
                                                            </tr>
                                                            <tr>
                                                                <th class="ps-0" scope="row">Other Name :</th>
                                                                <td class="text-muted"><?= $user_details->othername ?></td>
                                                            </tr>
                                                            <tr>
                                                                <th class="ps-0" scope="row">Mobile :</th>
                                                                <td class="text-muted"><?= $user_details->tel ?></td>
                                                            </tr>
                                                            <tr>
                                                                <th class="ps-0" scope="row">E-mail :</th>
                                                                <td class="text-muted"><?= $user_details->email ?></td>
                                                            </tr>

                                                            <tr>
                                                                <th class="ps-0" scope="row">Registered On</th>
                                                                <td class="text-muted"><?= date('d/m/Y', strtotime($user_details->date_created)) ?></td>
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div><!-- end card body -->
                                        </div><!-- end card -->



                                    </div>
                                    <!--end col-->

                                </div>
                                <!--end row-->
                            </div>
                            <div class="tab-pane fade" id="activities" role="tabpanel">
                                <div class="card">
                                    <div class="card-body">
                                        <h5 class="card-title mb-3">Current Borrowed Books</h5>
                                        <div class="acitivity-timeline">
                                            <div class="table-responsive mt-3 mb-1">
                                                <table id="myTable" class="table table-bordered table-striped">
                                                    <thead class="table-light">
                                                        <tr>
                                                            <th scope="col">
                                                                S/No.
                                                            </th>

                                                            <th class="sort" data-sort="date">Borrowed Book</th>
                                                            <th class="sort" data-sort="date">Copies</th>
                                                            <th class="sort" data-sort="date">Return Status</th>
                                                            <th class="sort" data-sort="date">Return Date</th>
                                                            <th class="sort" data-sort="date">Remaining Days</th>
                                                            <th class="sort" data-sort="action">Action</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody class="list form-check-all">

                                                        <?php

                                                        $all_requests = $db->where('aprove_status', 1)->where('return_status IS NULL')->where('student_id', $user_id)->get('borrow_requests');

                                                        $sn = 0;
                                                        foreach ($all_requests as $value):

                                                            $book_details = $db->where("id", $value->book_id)->getOne("books");

                                                            $sn++;
                                                        ?>
                                                            <tr>
                                                                <th scope="row">
                                                                    <?= $sn ?>
                                                                </th>


                                                                <td><?= $book_details->title  ?></td>
                                                                <td><?= $value->no_of_copies ?></td>
                                                                <td><span class="badge bg-info">Pending</span></td>
                                                                <td class="date"><?= date('d/m/Y', strtotime($value->return_date)) ?></td>
                                                                <td><?php
                                                                    $days = getBorrowedBookRemainingDays(date('y-m-d', strtotime($value->return_date)));
                                                                    if ($days <  1) {
                                                                        echo '<span class="badge bg-danger">Overdue by ' . abs($days) . ' days</span>';
                                                                    } else {
                                                                        echo $days . ' Days';
                                                                    }

                                                                    ?></td>

                                                                <td>
                                                                    <a title='View Details' href="index.php?page=req_details&id=<?= $value->id ?>" class="btn btn-sm btn-success " href=""><i class="fas fa-eye"></i> </a>
                                                                </td>
                                                            </tr>
                                                        <?php endforeach; ?>
                                                    </tbody>
                                                </table>

                                            </div>
                                        </div>
                                    </div>
                                    <!--end card-body-->
                                </div>
                                <!--end card-->
                            </div>
                            <!--end tab-pane-->
                            <div class="tab-pane fade" id="projects" role="tabpanel">
                                <div class="card">
                                    <div class="card-body">
                                        <h5 class="card-title mb-3">Borrow History</h5>
                                        <div class="acitivity-timeline">
                                            <div class="table-responsive mt-3 mb-1">
                                                <table id="myTable" class="table table-bordered table-striped">
                                                    <thead class="table-light">
                                                        <tr>
                                                            <th scope="col">
                                                                S/No.
                                                            </th>

                                                            <th class="sort" data-sort="date">Borrowed Book</th>
                                                            <th class="sort" data-sort="date">Copies</th>
                                                            <th class="sort" data-sort="date">Borrow Date</th>
                                                            <th class="sort" data-sort="date">Due Date</th>
                                                            <th class="sort" data-sort="date">Return Date</th>
                                                            <th class="sort" data-sort="date">Overdue Status</th>
                                                            <th class="sort" data-sort="action">Action</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody class="list form-check-all">

                                                        <?php

                                                        $all_requests = $db->where('aprove_status', 1)->where('return_status IS NOT NULL')->where('student_id', $user_id)->get('borrow_requests');

                                                        $sn = 0;
                                                        foreach ($all_requests as $value):

                                                            $book_details = $db->where("id", $value->book_id)->getOne("books");

                                                            $sn++;
                                                        ?>
                                                            <tr>
                                                                <th scope="row">
                                                                    <?= $sn ?>
                                                                </th>


                                                                <td><?= $book_details->title  ?></td>

                                                                <td><?= $value->no_of_copies ?></td>
                                                                <td><?= date('d/m/Y', strtotime($value->date_approved)) ?></td>
                                                                <td class="date"><?= date('d/m/Y', strtotime($value->return_date)) ?></td>
                                                                <?php if ($value->return_status == 1) {
                                                                    echo '<td class="date">' . date("d/m/Y", strtotime($value->returned_on)) . '</td>';
                                                                } else if ($value->return_status == 3) {
                                                                    echo '<td><span class="badge bg-danger">lost</span></td>';
                                                                } else {
                                                                    echo '<td><span class="badge bg-info">Pending</span></td><td>___</td>';
                                                                } ?></td>
                                                                <?php if ($value->return_status == 3) {
                                                                    echo ' <td><span class="badge bg-danger">Yes</span></td>';
                                                                } else {
                                                                    if ($value->returned_on > $value->return_date) {

                                                                        echo ' <td><span class="badge bg-danger">Yes</span></td>';
                                                                    } else {
                                                                        echo ' <td><span class="badge bg-info">Not</span></td>';
                                                                    }
                                                                }

                                                                ?>


                                                                <td>
                                                                    <a title='View Details' href="index.php?page=borrow_history&id=<?= $value->id ?>" class="btn btn-sm btn-success " href=""><i class="fas fa-eye"></i> </a>
                                                                </td>
                                                            </tr>
                                                        <?php endforeach; ?>
                                                    </tbody>
                                                </table>

                                            </div>
                                        </div>
                                    </div>
                                    <!--end card-body-->
                                </div>
                                <!--end card-->
                            </div>

                        </div>
                        <!--end tab-content-->
                    </div>
                </div>
                <!--end col-->
            </div>
            <!--end row-->

        </div><!-- container-fluid -->
    </div><!-- End Page-content -->

</div><!-- end main content-->

</div>
<!-- END layout-wrapper -->