<?php
$manage_books_array = ['all_books', 'edit_book', 'current_books', 'book_copies', 'book_details', 'inventory_update', 'edit_purchases', 'damaged_books', 'edit_damage'];
$bookings = ['requistions', 'borrowed_books', 'req_details'];
$genal_settings = ['categories', 'system_setup', 'all_classes', 'edit_category', 'edit_class'];
$users = ['all_libs', 'all_students', 'all_admins', 'student_profile'];
$borrow_history = ['trans_history', 'borrow_history'];
$report_pages = ['most_borrowing_students', 'most_borrowed_books', 'lost_books', 'over_due_books'];
$user_image = (empty($global_var['user']['photo'])) ? "/layout/assets/images/users/avatar-10.jpg" : $global_var['user']['photo'];
$pending_requests = count(
    $db->orderBy('id', 'DESC')
        ->where('request_date', getCurrentDateOnly())
        ->where('aprove_status IS NULL')
        ->get('borrow_requests')
);


?>
<header id="page-topbar">
    <div class="layout-width">
        <div class="navbar-header">
            <div class="d-flex">
                <!-- LOGO -->
                <div class="navbar-brand-box horizontal-logo">
                    <a href="<?= $global_var['site_url'] ?>" class="logo logo-dark">
                        <span class="logo-sm">
                            <img src="<?= $global_var['site_url'] . $global_var['config']['logo'] ?>" alt="" height="22">
                        </span>
                        <span class="logo-lg">
                            <img src="<?= $global_var['site_url'] . $global_var['config']['logo']  ?>" alt="" height="17">
                        </span>
                    </a>

                    <a href="<?= $global_var['site_url'] ?>" class="logo logo-light">
                        <span class="logo-sm">
                            <img src="<?= $global_var['site_url'] . $global_var['config']['logo']  ?>" alt="" height="22">
                        </span>
                        <span class="logo-lg">
                            <img src="<?= $global_var['site_url'] . $global_var['config']['logo'] ?>" alt="" height="17">
                        </span>
                    </a>
                </div>

                <button type="button" class="btn btn-sm px-3 fs-16 header-item vertical-menu-btn topnav-hamburger" id="topnav-hamburger-icon">
                    <span class="hamburger-icon">
                        <span></span>
                        <span></span>
                        <span></span>
                    </span>
                </button>

                <!-- App Search-->
                <form class="app-search d-none d-md-block">
                    <div class="position-relative">
                        <input type="text" class="form-control" placeholder="Search Book..." autocomplete="off" id="search-options" value="">
                        <span class="mdi mdi-magnify search-widget-icon"></span>
                        <span class="mdi mdi-close-circle search-widget-icon search-widget-icon-close d-none" id="search-close-options"></span>
                    </div>
                    <div class="dropdown-menu dropdown-menu-lg" id="search-dropdown">
                        <div data-simplebar style="max-height: 320px;">

                            <div class="notification-list">
                                <?php foreach ($db->get("books") as $book): ?>
                                    <!-- item -->
                                    <a href="index.php?page=all_books" class="dropdown-item notify-item py-2">
                                        <div class="d-flex">

                                            <div class="flex-grow-1">
                                                <h6 class="m-0"><?= $book->title ?></h6>
                                                <span class="fs-11 mb-0 text-muted"><?= $book->author ?></span>
                                            </div>
                                        </div>
                                    </a>
                                <?php endforeach; ?>
                                <!-- item -->

                            </div>
                        </div>

                        <div class="text-center pt-3 pb-1">
                            <a href="index.php?page=all_books" class="btn btn-primary btn-sm">View All Books <i class="ri-arrow-right-line ms-1"></i></a>
                        </div>
                    </div>
                </form>
            </div>

            <div class="d-flex align-items-center">



                <div class="ms-1 header-item d-none d-sm-flex">
                    <button type="button" class="btn btn-icon btn-topbar btn-ghost-secondary rounded-circle" data-toggle="fullscreen">
                        <i class='bx bx-fullscreen fs-22'></i>
                    </button>
                </div>

                <div class="ms-1 header-item d-none d-sm-flex">
                    <button type="button" class="btn btn-icon btn-topbar btn-ghost-secondary rounded-circle light-dark-mode">
                        <i class='bx bx-moon fs-22'></i>
                    </button>
                </div>

                <div class="dropdown topbar-head-dropdown ms-1 header-item" id="notificationDropdown">
                    <!-- <button type="button" class="btn btn-icon btn-topbar btn-ghost-secondary rounded-circle" id="page-header-notifications-dropdown" data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-haspopup="true" aria-expanded="false">
                        <i class='bx bx-bell fs-22'></i>
                        <span class="position-absolute topbar-badge fs-10 translate-middle badge rounded-pill bg-danger">3<span class="visually-hidden">unread messages</span></span>
                    </button> -->
                    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-end p-0" aria-labelledby="page-header-notifications-dropdown">

                        <div class="dropdown-head bg-primary bg-pattern rounded-top">
                            <div class="p-3">
                                <div class="row align-items-center">
                                    <div class="col">
                                        <h6 class="m-0 fs-16 fw-semibold text-white"> Notifications </h6>
                                    </div>
                                    <div class="col-auto dropdown-tabs">
                                        <span class="badge bg-light-subtle text-body fs-13"> 4 New</span>
                                    </div>
                                </div>
                            </div>

                            <div class="px-2 pt-2">
                                <ul class="nav nav-tabs dropdown-tabs nav-tabs-custom" data-dropdown-tabs="true" id="notificationItemsTab" role="tablist">
                                    <li class="nav-item waves-effect waves-light">
                                        <a class="nav-link active" data-bs-toggle="tab" href="#all-noti-tab" role="tab" aria-selected="true">
                                            All (4)
                                        </a>
                                    </li>
                                    <li class="nav-item waves-effect waves-light">
                                        <a class="nav-link" data-bs-toggle="tab" href="#messages-tab" role="tab" aria-selected="false">
                                            Messages
                                        </a>
                                    </li>
                                    <li class="nav-item waves-effect waves-light">
                                        <a class="nav-link" data-bs-toggle="tab" href="#alerts-tab" role="tab" aria-selected="false">
                                            Alerts
                                        </a>
                                    </li>
                                </ul>
                            </div>

                        </div>

                        <div class="tab-content position-relative" id="notificationItemsTabContent">
                            <div class="tab-pane fade show active py-2 ps-2" id="all-noti-tab" role="tabpanel">
                                <div data-simplebar style="max-height: 300px;" class="pe-2">
                                    <div class="text-reset notification-item d-block dropdown-item position-relative">
                                        <div class="d-flex">
                                            <div class="avatar-xs me-3 flex-shrink-0">
                                                <span class="avatar-title bg-info-subtle text-info rounded-circle fs-16">
                                                    <i class="bx bx-badge-check"></i>
                                                </span>
                                            </div>
                                            <div class="flex-grow-1">
                                                <a href="#!" class="stretched-link">
                                                    <h6 class="mt-0 mb-2 lh-base">Your <b>Elite</b> author Graphic
                                                        Optimization <span class="text-secondary">reward</span> is
                                                        ready!
                                                    </h6>
                                                </a>
                                                <p class="mb-0 fs-11 fw-medium text-uppercase text-muted">
                                                    <span><i class="mdi mdi-clock-outline"></i> Just 30 sec ago</span>
                                                </p>
                                            </div>
                                            <div class="px-2 fs-15">
                                                <div class="form-check notification-check">
                                                    <input class="form-check-input" type="checkbox" value="" id="all-notification-check01">
                                                    <label class="form-check-label" for="all-notification-check01"></label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="text-reset notification-item d-block dropdown-item position-relative">
                                        <div class="d-flex">
                                            <img src="<?= $global_var['site_url'] ?>/layout/assets/images/users/avatar-2.jpg" class="me-3 rounded-circle avatar-xs flex-shrink-0" alt="user-pic">
                                            <div class="flex-grow-1">
                                                <a href="#!" class="stretched-link">
                                                    <h6 class="mt-0 mb-1 fs-13 fw-semibold">Angela Bernier</h6>
                                                </a>
                                                <div class="fs-13 text-muted">
                                                    <p class="mb-1">Answered to your comment on the cash flow forecast's
                                                        graph 🔔.</p>
                                                </div>
                                                <p class="mb-0 fs-11 fw-medium text-uppercase text-muted">
                                                    <span><i class="mdi mdi-clock-outline"></i> 48 min ago</span>
                                                </p>
                                            </div>
                                            <div class="px-2 fs-15">
                                                <div class="form-check notification-check">
                                                    <input class="form-check-input" type="checkbox" value="" id="all-notification-check02">
                                                    <label class="form-check-label" for="all-notification-check02"></label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="text-reset notification-item d-block dropdown-item position-relative">
                                        <div class="d-flex">
                                            <div class="avatar-xs me-3 flex-shrink-0">
                                                <span class="avatar-title bg-danger-subtle text-danger rounded-circle fs-16">
                                                    <i class='bx bx-message-square-dots'></i>
                                                </span>
                                            </div>
                                            <div class="flex-grow-1">
                                                <a href="#!" class="stretched-link">
                                                    <h6 class="mt-0 mb-2 fs-13 lh-base">You have received <b class="text-success">20</b> new messages in the conversation
                                                    </h6>
                                                </a>
                                                <p class="mb-0 fs-11 fw-medium text-uppercase text-muted">
                                                    <span><i class="mdi mdi-clock-outline"></i> 2 hrs ago</span>
                                                </p>
                                            </div>
                                            <div class="px-2 fs-15">
                                                <div class="form-check notification-check">
                                                    <input class="form-check-input" type="checkbox" value="" id="all-notification-check03">
                                                    <label class="form-check-label" for="all-notification-check03"></label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="text-reset notification-item d-block dropdown-item position-relative">
                                        <div class="d-flex">
                                            <img src="<?= $global_var['site_url'] ?>/layout/assets/images/users/avatar-8.jpg" class="me-3 rounded-circle avatar-xs flex-shrink-0" alt="user-pic">
                                            <div class="flex-grow-1">
                                                <a href="#!" class="stretched-link">
                                                    <h6 class="mt-0 mb-1 fs-13 fw-semibold">Maureen Gibson</h6>
                                                </a>
                                                <div class="fs-13 text-muted">
                                                    <p class="mb-1">We talked about a project on linkedin.</p>
                                                </div>
                                                <p class="mb-0 fs-11 fw-medium text-uppercase text-muted">
                                                    <span><i class="mdi mdi-clock-outline"></i> 4 hrs ago</span>
                                                </p>
                                            </div>
                                            <div class="px-2 fs-15">
                                                <div class="form-check notification-check">
                                                    <input class="form-check-input" type="checkbox" value="" id="all-notification-check04">
                                                    <label class="form-check-label" for="all-notification-check04"></label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="my-3 text-center view-all">
                                        <button type="button" class="btn btn-soft-success waves-effect waves-light">View
                                            All Notifications <i class="ri-arrow-right-line align-middle"></i></button>
                                    </div>
                                </div>

                            </div>

                            <div class="tab-pane fade py-2 ps-2" id="messages-tab" role="tabpanel" aria-labelledby="messages-tab">
                                <div data-simplebar style="max-height: 300px;" class="pe-2">
                                    <div class="text-reset notification-item d-block dropdown-item">
                                        <div class="d-flex">
                                            <img src="<?= $global_var['site_url'] ?>/layout/assets/images/users/avatar-3.jpg" class="me-3 rounded-circle avatar-xs" alt="user-pic">
                                            <div class="flex-grow-1">
                                                <a href="#!" class="stretched-link">
                                                    <h6 class="mt-0 mb-1 fs-13 fw-semibold">James Lemire</h6>
                                                </a>
                                                <div class="fs-13 text-muted">
                                                    <p class="mb-1">We talked about a project on linkedin.</p>
                                                </div>
                                                <p class="mb-0 fs-11 fw-medium text-uppercase text-muted">
                                                    <span><i class="mdi mdi-clock-outline"></i> 30 min ago</span>
                                                </p>
                                            </div>
                                            <div class="px-2 fs-15">
                                                <div class="form-check notification-check">
                                                    <input class="form-check-input" type="checkbox" value="" id="messages-notification-check01">
                                                    <label class="form-check-label" for="messages-notification-check01"></label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="text-reset notification-item d-block dropdown-item">
                                        <div class="d-flex">
                                            <img src="<?= $global_var['site_url'] ?>/layout/assets/images/users/avatar-2.jpg" class="me-3 rounded-circle avatar-xs" alt="user-pic">
                                            <div class="flex-grow-1">
                                                <a href="#!" class="stretched-link">
                                                    <h6 class="mt-0 mb-1 fs-13 fw-semibold">Angela Bernier</h6>
                                                </a>
                                                <div class="fs-13 text-muted">
                                                    <p class="mb-1">Answered to your comment on the cash flow forecast's
                                                        graph 🔔.</p>
                                                </div>
                                                <p class="mb-0 fs-11 fw-medium text-uppercase text-muted">
                                                    <span><i class="mdi mdi-clock-outline"></i> 2 hrs ago</span>
                                                </p>
                                            </div>
                                            <div class="px-2 fs-15">
                                                <div class="form-check notification-check">
                                                    <input class="form-check-input" type="checkbox" value="" id="messages-notification-check02">
                                                    <label class="form-check-label" for="messages-notification-check02"></label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="text-reset notification-item d-block dropdown-item">
                                        <div class="d-flex">
                                            <img src="<?= $global_var['site_url'] ?>/layout/assets/images/users/avatar-6.jpg" class="me-3 rounded-circle avatar-xs" alt="user-pic">
                                            <div class="flex-grow-1">
                                                <a href="#!" class="stretched-link">
                                                    <h6 class="mt-0 mb-1 fs-13 fw-semibold">Kenneth Brown</h6>
                                                </a>
                                                <div class="fs-13 text-muted">
                                                    <p class="mb-1">Mentionned you in his comment on 📃 invoice #12501.
                                                    </p>
                                                </div>
                                                <p class="mb-0 fs-11 fw-medium text-uppercase text-muted">
                                                    <span><i class="mdi mdi-clock-outline"></i> 10 hrs ago</span>
                                                </p>
                                            </div>
                                            <div class="px-2 fs-15">
                                                <div class="form-check notification-check">
                                                    <input class="form-check-input" type="checkbox" value="" id="messages-notification-check03">
                                                    <label class="form-check-label" for="messages-notification-check03"></label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="text-reset notification-item d-block dropdown-item">
                                        <div class="d-flex">
                                            <img src="<?= $global_var['site_url'] ?>/layout/assets/images/users/avatar-8.jpg" class="me-3 rounded-circle avatar-xs" alt="user-pic">
                                            <div class="flex-grow-1">
                                                <a href="#!" class="stretched-link">
                                                    <h6 class="mt-0 mb-1 fs-13 fw-semibold">Maureen Gibson</h6>
                                                </a>
                                                <div class="fs-13 text-muted">
                                                    <p class="mb-1">We talked about a project on linkedin.</p>
                                                </div>
                                                <p class="mb-0 fs-11 fw-medium text-uppercase text-muted">
                                                    <span><i class="mdi mdi-clock-outline"></i> 3 days ago</span>
                                                </p>
                                            </div>
                                            <div class="px-2 fs-15">
                                                <div class="form-check notification-check">
                                                    <input class="form-check-input" type="checkbox" value="" id="messages-notification-check04">
                                                    <label class="form-check-label" for="messages-notification-check04"></label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="my-3 text-center view-all">
                                        <button type="button" class="btn btn-soft-success waves-effect waves-light">View
                                            All Messages <i class="ri-arrow-right-line align-middle"></i></button>
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane fade p-4" id="alerts-tab" role="tabpanel" aria-labelledby="alerts-tab"></div>

                            <div class="notification-actions" id="notification-actions">
                                <div class="d-flex text-muted justify-content-center">
                                    Select <div id="select-content" class="text-body fw-semibold px-1">0</div> Result <button type="button" class="btn btn-link link-danger p-0 ms-3" data-bs-toggle="modal" data-bs-target="#removeNotificationModal">Remove</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="dropdown ms-sm-3 header-item topbar-user">
                    <button type="button" class="btn" id="page-header-user-dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="d-flex align-items-center">
                            <img class="rounded-circle header-profile-user" src="<?= $global_var['site_url'] . $user_image ?>" alt="Header Avatar">
                            <span class="text-start ms-xl-2">
                                <span class="d-none d-xl-inline-block ms-1 fw-medium user-name-text"><?= $global_var['user']['firstname'] . ' ' . $global_var['user']['lastname'] ?></span>
                                <span class="d-none d-xl-block ms-1 fs-12 user-name-sub-text">
                                    <?php
                                    if ($global_var['user']['user_type'] == 'stud') {
                                        echo "Student";
                                    } elseif ($global_var['user']['user_type'] == 'lib') {
                                        echo "Librarian";
                                    } else {
                                        echo "Admin";
                                    }
                                    ?>
                                </span>
                            </span>
                        </span>
                    </button>
                    <div class="dropdown-menu dropdown-menu-end">
                        <!-- item-->
                        <h6 class="dropdown-header">Welcome <?= $global_var['user']['firstname'] ?>!</h6>
                        <a class="dropdown-item" href="index.php?page=user_profile"><i class="mdi mdi-account-circle text-muted fs-16 align-middle me-1"></i> <span class="align-middle">Profile</span></a>
                        <!-- <a class="dropdown-item" href="apps-chat.html"><i class="mdi mdi-message-text-outline text-muted fs-16 align-middle me-1"></i> <span class="align-middle">Messages</span></a> -->

                        <!-- <a class="dropdown-item" href="pages-faqs.html"><i class="mdi mdi-lifebuoy text-muted fs-16 align-middle me-1"></i> <span class="align-middle">Help</span></a> -->
                        <div class="dropdown-divider"></div>

                        <!-- <a class="dropdown-item" href="pages-profile-settings.html"><span class="badge bg-success-subtle text-success mt-1 float-end"></span><i class="mdi mdi-cog-outline text-muted fs-16 align-middle me-1"></i> <span class="align-middle">Settings</span></a> -->

                        <a class="dropdown-item" href="index.php?page=logout"><i class="mdi mdi-logout text-muted fs-16 align-middle me-1"></i> <span class="align-middle" data-key="t-logout">Logout</span></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- ========== App Menu ========== -->
<div class="app-menu navbar-menu">
    <!-- LOGO -->
    <div class="navbar-brand-box">
        <!-- Dark Logo-->
        <a href="<?= $global_var['site_url'] ?>" class="logo logo-dark">
            <span class="logo-sm">
                <img src="<?= $global_var['site_url'] . $global_var['config']['logo']  ?>" alt="" height="22">
            </span>
            <span class="logo-lg">
                <img src="<?= $global_var['site_url'] . $global_var['config']['logo']  ?>" alt="" height="17">
            </span>
        </a>
        <!-- Light Logo-->
        <a href="<?= $global_var['site_url'] ?>" class="logo logo-light">
            <span class="logo-sm">
                <img src="<?= $global_var['site_url'] . $global_var['config']['logo']  ?>" alt="" height="22">
            </span>
            <span class="logo-lg mt-2">
                <img width="100px" height="100px" src="<?= $global_var['site_url'] . $global_var['config']['logo']  ?>" alt="" height="17">
            </span>
        </a>
        <button type="button" class="btn btn-sm p-0 fs-20 header-item float-end btn-vertical-sm-hover" id="vertical-hover">
            <i class="ri-record-circle-line"></i>
        </button>
    </div>

    <div id="scrollbar">
        <div class="container-fluid">

            <div id="two-column-menu">
            </div>
            <ul class="navbar-nav" id="navbar-nav">
                <li class="menu-title"><span data-key="t-menu">Menu</span></li>
                <li class="nav-item">
                    <a class="nav-link menu-link <?= (($page == 'index') ? 'active' : '') ?>" href="index.php?page=index" role="button" aria-expanded="false" aria-controls="sidebarDashboards">
                        <i class="ri-dashboard-2-line"></i> <span data-key="t-dashboards">Dashboard</span>
                    </a>

                </li> <!-- end Dashboard Menu -->

                <li class="nav-item">
                    <a class="nav-link menu-link"
                        href="#sidebarApps"
                        data-bs-toggle="collapse"
                        role="button"
                        aria-expanded="<?= (in_array($page, $manage_books_array) ? 'true' : '') ?>"
                        aria-controls="sidebarApps">
                        <i class="ri-book-shelf-line"></i> <span data-key="t-apps"><?= ($global_var['user']['user_type'] != 'stud') ? 'Books Management' : 'Library Books' ?></span>
                    </a>

                    <div class="collapse menu-dropdown <?= (in_array($page, $manage_books_array) ? 'show' : '') ?>" id="sidebarApps">
                        <ul class="nav nav-sm flex-column">

                            <li class="nav-item">
                                <a href="index.php?page=all_books" class="nav-link <?= (($page == 'all_books') ? 'active' : '') ?>" data-key="t-chat">View All Books </a>
                            </li>
                            <?php if ($global_var['user']['user_type'] != 'stud') { ?>
                                <li class="nav-item">
                                    <a data-bs-toggle="modal" data-bs-target="#register" class="nav-link"> <span data-key="t-file-manager">Add New Book</span></a>
                                </li>
                                <li class="nav-item">
                                    <a href="index.php?page=current_books" class="nav-link <?= (($page == 'current_books') ? 'active' : '') ?>"> <span data-key="t-to-do">View Current Books</span></a>
                                </li>
                                <li class="nav-item">
                                    <a href="index.php?page=inventory_update" class="nav-link <?= (($page == 'inventory_update') ? 'active' : '') ?>"> <span data-key="t-to-do">Inventory update</span></a>
                                </li>
                                <li class="nav-item">
                                    <a href="index.php?page=damaged_books" class="nav-link <?= (($page == 'damaged_books') ? 'active' : '') ?>"> <span data-key="t-to-do">Damaged Books</span></a>
                                </li>
                            <?php } ?>
                            <!--  <li class="nav-item">
                                            <a href="apps-api-key.html" class="nav-link" data-key="t-api-key">API Key</a>
                                        </li> -->
                        </ul>
                    </div>
                </li>

                <li class="nav-item">
                    <a class="nav-link menu-link" href="#sidebarLayouts1" data-bs-toggle="collapse" role="button" aria-expanded="<?= (in_array($page, $bookings) ? 'true' : '') ?>" aria-controls="sidebarLayouts">
                        <i class="ri-layout-3-line"></i> <span data-key="t-layouts">Borrow Requests
                            <span class="topbar-badge fs-30 badge rounded-pill bg-secondary"><?= ($global_var['user']['user_type'] == 'stud') ?  count(
                                                                                                    $db->orderBy('id', 'DESC')
                                                                                                        ->where('student_id', $global_var['user']['id'])
                                                                                                        ->where('aprove_status', 1)
                                                                                                        ->where('return_status IS NULL')
                                                                                                        ->get('borrow_requests')
                                                                                                ) :

                                                                                                    $pending_requests ?></span>
                        </span>
                    </a>
                    <div class="collapse menu-dropdown <?= (in_array($page, $bookings) ? 'show' : '') ?>" id="sidebarLayouts1">
                        <ul class="nav nav-sm flex-column">
                            <li class="nav-item">
                                <a href="index.php?page=requistions" class="nav-link <?= (($page == 'requistions') ? 'active' : '') ?>" data-key="t-horizontal">All Requests
                                    <?php if ($global_var['user']['user_type'] == 'lib') { ?>
                                        <span class="badge bg-light-subtle text-body fs-13">
                                            <?= $pending_requests

                                            ?> New</span>
                                    <?php } ?>
                                </a>
                            </li>

                            <li class="nav-item">
                                <a href="index.php?page=borrowed_books" class="nav-link <?= (($page == 'borrowed_books') ? 'active' : '') ?>" data-key="t-hovered">Current Borrowed Books</a>
                                <?php if ($global_var['user']['user_type'] == 'stud') { ?>
                                    <span class="topbar-badge fs-30 badge rounded-pill bg-secondary">
                                        <?= count(
                                            $db->orderBy('id', 'DESC')
                                                ->where('student_id', $global_var['user']['id'])
                                                ->where('aprove_status', 1)
                                                ->where('return_status IS NULL')
                                                ->get('borrow_requests')
                                        );

                                        ?><i> Borrowed </i></span>
                                <?php } ?>
                            </li>
                        </ul>
                    </div>
                </li> <!-- end Dashboard Menu -->
                <li class="nav-item">
                    <a class="nav-link menu-link <?= ($page == 'trans_history') ? 'active' : '' ?>" href="index.php?page=trans_history" role="button">
                        <i class="ri-folder-history-line"></i></i> <span data-key="t-layouts">Borrow History</span>
                    </a>

                </li> <!-- end Dashboard Menu -->


                <li class="menu-title"><i class="ri-more-fill"></i> <span data-key="t-components">Reports</span></li>

                <li class="nav-item">
                    <a class="nav-link menu-link" href="#sidebarAdvanceUI" data-bs-toggle="collapse" role="button" aria-expanded="<?= (in_array($page, $report_pages) ? 'true' : '') ?>" aria-controls="sidebarAdvanceUI">
                        <i class="ri-stack-line"></i> <span data-key="t-advance-ui">View Reports</span>
                    </a>
                    <div class="collapse menu-dropdown <?= (in_array($page, $report_pages) ? 'show' : '') ?>" id="sidebarAdvanceUI">
                        <ul class="nav nav-sm flex-column ">
                            <li class="nav-item">
                                <a href="index.php?page=most_borrowed_books" class="nav-link <?= ($page == 'most_borrowed_books') ? 'active' : '' ?>" data-key="t-sweet-alerts">View Most Borrowed Book
                                </a>
                                <?php if ($global_var['user']['user_type'] != 'stud') { ?>
                                    <a href="index.php?page=most_borrowing_students" class="nav-link <?= ($page == 'most_borrowing_students') ? 'active' : '' ?>" data-key="t-sweet-alerts">View Most Borrowing Students
                                    </a>
                                <?php } ?>
                                <a href="index.php?page=over_due_books" class="nav-link <?= ($page == 'over_due_books') ? 'active' : '' ?>" data-key="t-sweet-alerts">Over Due Books
                                    <span class="topbar-badge fs-30 badge rounded-pill bg-danger"><?= ($global_var['user']['user_type'] == 'stud') ?
                                                                                                        $db->where('return_date', getCurrentDateOnly(), '<')
                                                                                                        ->where('aprove_status', 1)
                                                                                                        ->where('student_id', $global_var['user']['id'])
                                                                                                        ->where('return_status IS NULL')
                                                                                                        ->getValue('borrow_requests', 'SUM(no_of_copies)') ?? 0 : $db->where('return_date', getCurrentDateOnly(), '<')
                                                                                                        ->where('aprove_status', 1)
                                                                                                        ->where('student_id', $global_var['user']['id'])
                                                                                                        ->where('return_status IS NULL')
                                                                                                        ->getValue('borrow_requests', 'SUM(no_of_copies)') ?? 0;
                                                                                                    ?>
                                    </span>
                                </a>
                                <a href="index.php?page=lost_books" class="nav-link <?= ($page == 'lost_books') ? 'active' : '' ?>" data-key="t-sweet-alerts">View Lost Books
                                </a>
                            </li>

                        </ul>
                    </div>
                </li>


                <?php if ($global_var['user']['user_type'] != 'stud') { ?>
                    <li class="menu-title"><i class="ri-more-fill"></i> <span data-key="t-pages"><?= (($global_var['user']['user_type'] == 'admin') ? 'Settings' : 'Users') ?></span></li>

                    <li class="nav-item">
                        <a class="nav-link menu-link" href="#sidebarAuth" data-bs-toggle="collapse" role="button" aria-expanded="<?= (in_array($page, $users) ? 'true' : '') ?>" aria-controls="sidebarAuth">
                            <i class="ri-account-circle-line"></i> <span data-key="t-authentication"><?= (($global_var['user']['user_type'] == 'admin') ? 'Users' : 'Students') ?></span>
                        </a>
                        <div class="collapse menu-dropdown <?= (in_array($page, $users) ? 'show' : '') ?>" id="sidebarAuth">
                            <ul class="nav nav-sm flex-column">

                                <li class="nav-item">
                                    <a href="index.php?page=all_students" class="nav-link <?= (($page == 'all_students') ? 'active' : '') ?>" data-key="t-basic">All Students
                                    </a>
                                </li>

                                <?php if ($global_var['user']['user_type'] == 'admin') { ?>
                                    <li class="nav-item">
                                        <a href="index.php?page=all_libs" class="nav-link <?= (($page == 'all_libs') ? 'active' : '') ?>" data-key="t-cover"> All Librarians
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="index.php?page=all_admins" class="nav-link <?= (($page == 'all_admins') ? 'active' : '') ?>" data-key="t-cover">All Admins
                                        </a>
                                    </li>
                                <?php } ?>
                            </ul>
                        </div>
                    </li>
                <?php }
                if ($global_var['user']['user_type'] == 'admin') { ?>
                    <li class="nav-item">
                        <a class="nav-link menu-link" href="#settings" data-bs-toggle="collapse" role="button" aria-expanded="<?= (in_array($page, $genal_settings) ? 'true' : '') ?>" aria-controls="settings">
                            <i class="ri-pages-line"></i> <span data-key="t-pages">General Settings</span>
                        </a>
                        <div class="collapse menu-dropdown <?= (in_array($page, $genal_settings) ? 'show' : '') ?>" id="settings">
                            <ul class="nav nav-sm flex-column ">
                                <li class="nav-item">
                                    <a href="index.php?page=system_setup" class="nav-link <?= (($page == 'system_setup') ? 'active' : '') ?>" data-key="t-starter"> System Setup </a>
                                </li>
                                <li class="nav-item">
                                    <a href="index.php?page=categories" class="nav-link <?= (($page == 'categories') ? 'active' : '') ?>" data-key="t-starter">Book Categories </a>
                                </li>

                                <li class="nav-item">
                                    <a href="index.php?page=all_classes" class="nav-link  <?= (($page == 'all_classes') ? 'active' : '') ?>" data-key="t-privacy-policy">All Classes</a>
                                </li>
                                <li class="nav-item d-none">
                                    <a href="pages-term-conditions.html" class="nav-link" data-key="t-term-conditions">Term & Conditions</a>
                                </li>

                            </ul>
                        </div>
                    </li>
                <?php  } ?>

            </ul>
        </div>
        <!-- Sidebar -->
    </div>

    <div class="sidebar-background"></div>
</div>